async function streamAndIterate(path, func) {
    // Read the file
    const file = Bun.file(path) // The file with the original data

    let fieldIndex
    let count = 0

    // Taken and modified from StackOverflow
    const stream = await file.stream() // Stream the input file byte-by-byte
    const decoder = new TextDecoder()
    let buffer = "" // Store the data we are streaming to detect when there is a new line
    for await (const chunk of stream) {
        buffer += decoder.decode(chunk) // Append the chunk to the remaining data
        let lines = buffer.split(/\r?\n/); // When we get a new line, split the data into lines
        while (lines.length > 1) { // Loop through each line, except the last one
            const line = lines.shift()
            func(line)
            count++
            // console.log(`Checking line ${count}`)
        }
        buffer = lines[0]; // Discard all of the processed lines
    }

    // console.log("Finished!")
    // Write all of the stashed lines to the file and close the writer
}

const titleMap = {
    "Friendship is Magic, part 1": 101,
    "Friendship is Magic, part 2": 102,
    "The Ticket Master": 103,
    "Applebuck Season": 104,
    "Griffon the Brush Off": 105,
    "Boast Busters": 106,
    "Dragonshy": 107,
    "Look Before You Sleep": 108,
    "Bridle Gossip": 109,
    "Swarm of the Century": 110,
    "Winter Wrap Up": 111,
    "Call of the Cutie": 112,
    "Fall Weather Friends": 113,
    "Suited For Success": 114,
    "Feeling Pinkie Keen": 115,
    "Sonic Rainboom": 116,
    "Stare Master": 117,
    "The Show Stoppers": 118,
    "A Dog and Pony Show": 119,
    "Green Isn't Your Color": 120,
    "Over a Barrel": 121,
    "A Bird in the Hoof": 122,
    "The Cutie Mark Chronicles": 123,
    "Owl's Well That Ends Well": 124,
    "Party of One": 125,
    "The Best Night Ever": 126,
    "The Return of Harmony Part 1": 201,
    "The Return of Harmony Part 2": 202,
    "Lesson Zero": 203,
    "Luna Eclipsed": 204,
    "Sisterhooves Social": 205,
    "The Cutie Pox": 206,
    "May the Best Pet Win!": 207,
    "The Mysterious Mare Do Well": 208,
    "Sweet and Elite": 209,
    "Secret of My Excess": 210,
    "Hearth's Warming Eve": 211,
    "Family Appreciation Day": 212,
    "Baby Cakes": 213,
    "The Last Roundup": 214,
    "The Super Speedy Cider Squeezy 6000": 215,
    "Read It and Weep": 216,
    "Hearts and Hooves Day": 217,
    "A Friend in Deed": 218,
    "Putting Your Hoof Down": 219,
    "It's About Time": 220,
    "Dragon Quest": 221,
    "Hurricane Fluttershy": 222,
    "Ponyville Confidential": 223,
    "MMMystery on the Friendship Express": 224,
    "A Canterlot Wedding - Part 1": 225,
    "A Canterlot Wedding - Part 2": 226,
    "The Crystal Empire - Part 1": 301,
    "The Crystal Empire - Part 2": 302,
    "Too Many Pinkie Pies": 303,
    "One Bad Apple": 304,
    "Magic Duel": 305,
    "Sleepless in Ponyville": 306,
    "Wonderbolts Academy": 307,
    "Apple Family Reunion": 308,
    "Spike at Your Service": 309,
    "Keep Calm and Flutter On": 310,
    "Just for Sidekicks": 311,
    "Games Ponies Play": 312,
    "Magical Mystery Cure": 313,
    "Princess Twilight Sparkle - Part 1": 401,
    "Princess Twilight Sparkle - Part 2": 402,
    "Castle Mane-ia": 403,
    "Daring Don't": 404,
    "Flight to the Finish": 405,
    "Power Ponies": 406,
    "Bats!": 407,
    "Rarity Takes Manehattan": 408,
    "Pinkie Apple Pie": 409,
    "Rainbow Falls": 410,
    "Three's A Crowd": 411,
    "Pinkie Pride": 412,
    "Simple Ways": 413,
    "Filli Vanilli": 414,
    "Twilight Time": 415,
    "It Ain't Easy Being Breezies": 416,
    "Somepony to Watch Over Me": 417,
    "Maud Pie": 418,
    "For Whom the Sweetie Belle Toils": 419,
    "Leap of Faith": 420,
    "Testing Testing 1, 2, 3": 421,
    "Trade Ya!": 422,
    "Inspiration Manifestation": 423,
    "Equestria Games": 424,
    "Twilight's Kingdom - Part 1": 425,
    "Twilight's Kingdom - Part 2": 426,
    "The Cutie Map - Part 1": 501,
    "The Cutie Map - Part 2": 502,
    "Castle Sweet Castle": 503,
    "Bloom & Gloom": 504,
    "Tanks for the Memories": 505,
    "Appleoosa's Most Wanted": 506,
    "Make New Friends but Keep Discord": 507,
    "The Lost Treasure of Griffonstone": 508,
    "Slice of Life": 509,
    "Princess Spike": 510,
    "Party Pooped": 511,
    "Amending Fences": 512,
    "Do Princesses Dream of Magic Sheep?": 513,
    "Canterlot Boutique": 514,
    "Rarity Investigates!": 515,
    "Made in Manehattan": 516,
    "Brotherhooves Social": 517,
    "Crusaders of the Lost Mark": 518,
    "The One Where Pinkie Pie Knows": 519,
    "Hearthbreakers": 520,
    "Scare Master": 521,
    "What About Discord?": 522,
    "The Hooffields and McColts": 523,
    "The Mane Attraction": 524,
    "The Cutie Re-Mark - Part 1": 525,
    "The Cutie Re-Mark - Part 2": 526,
    "The Crystalling - Part 1": 601,
    "The Crystalling - Part 2": 602,
    "The Gift of the Maud Pie": 603,
    "On Your Marks": 604,
    "Gauntlet of Fire": 605,
    "No Second Prances": 606,
    "Newbie Dash": 607,
    "A Hearth's Warming Tail": 608,
    "The Saddle Row Review": 609,
    "Applejack's \"Day\" Off": 610,
    "Flutter Brutter": 611,
    "Spice Up Your Life": 612,
    "Stranger Than Fan Fiction": 613,
    "The Cart Before the Ponies": 614,
    "28 Pranks Later": 615,
    "The Times They Are A Changeling": 616,
    "Dungeons & Discords": 617,
    "Buckball Season": 618,
    "The Fault in Our Cutie Marks": 619,
    "Viva Las Pegasus": 620,
    "Every Little Thing She Does": 621,
    "P.P.O.V. (Pony Point of View)": 622,
    "Where the Apple Lies": 623,
    "Top Bolt": 624,
    "To Where and Back Again - Part 1": 625,
    "To Where and Back Again - Part 2": 626,
    "Celestial Advice": 701,
    "All Bottled Up": 702,
    "A Flurry of Emotions": 703,
    "Rock Solid Friendship": 704,
    "Fluttershy Leans In": 705,
    "Forever Filly": 706,
    "Parental Glideance": 707,
    "Hard to Say Anything": 708,
    "Honest Apple": 709,
    "A Royal Problem": 710,
    "Not Asking for Trouble": 711,
    "Discordant Harmony": 712,
    "The Perfect Pear": 713,
    "Fame and Misfortune": 714,
    "Triple Threat": 715,
    "Campfire Tales": 716,
    "To Change a Changeling": 717,
    "Daring Done?": 718,
    "It Isn't the Mane Thing About You": 719,
    "A Health of Information": 720,
    "Marks and Recreation": 721,
    "Once Upon a Zeppelin": 722,
    "Secrets and Pies": 723,
    "Uncommon Bond": 724,
    "Shadow Play - Part 1": 725,
    "Shadow Play - Part 2": 726,
    "School Daze - Part 1": 801,
    "School Daze - Part 2": 802,
    "The Maud Couple": 803,
    "Fake It 'Til You Make It": 804,
    "Grannies Gone Wild": 805,
    "Surf and or Turf": 806,
    "Horse Play": 807,
    "The Parent Map": 808,
    "Non-Compete Clause": 809,
    "The Break Up Break Down": 810,
    "Molt Down": 811,
    "Marks for Effort": 812,
    "The Mean 6": 813,
    "A Matter of Principals": 814,
    "The Hearth's Warming Club": 815,
    "Friendship University": 816,
    "The End in Friend": 817,
    "Yakity-Sax": 818,
    "Road to Friendship": 819,
    "The Washouts": 820,
    "A Rockhoof and a Hard Place": 821,
    "What Lies Beneath": 822,
    "Sounds of Silence": 823,
    "Father Knows Beast": 824,
    "School Raze - Part 1": 825,
    "School Raze - Part 2": 826,
    "The Beginning of the End - Part 1": 901,
    "The Beginning of the End - Part 2": 902,
    "Uprooted": 903,
    "Sparkle's Seven": 904,
    "The Point of No Return": 905,
    "Common Ground": 906,
    "She's All Yak": 907,
    "Frenemies": 908,
    "Sweet and Smoky": 909,
    "Going to Seed": 910,
    "Student Counsel": 911,
    "The Last Crusade": 912,
    "Between Dark and Dawn": 913,
    "The Last Laugh": 914,
    "2, 4, 6, Greaaat": 915,
    "A Trivial Pursuit": 916,
    "The Summer Sun Setback": 917,
    "She Talks to Angel": 918,
    "Dragon Dropped": 919,
    "A Horse Shoe-In": 920,
    "Daring Doubt": 921,
    "Growing Up is Hard to Do": 922,
    "The Big Mac Question": 923,
    "The Ending of the End - Part 1": 924,
    "The Ending of the End - Part 2": 925,
    "The Last Problem": 926,
    "A-Dressing Memories": 927,
    "Cakes for the Memories": 928,
    "Memnagerie": 929,
    "Deep Tissue Memories": 930,
    "Harvesting Memories": 931,
    "Memories and More": 932
}
const speakers = {
    "Narrator": 1,
    "Narrator, Twilight Sparkle": 2,
    "Twilight Sparkle": 3,
    "Twinkleshine": 4,
    "Spike": 5,
    "Royal guards": 6,
    "Pinkie Pie": 7,
    "Applejack": 8,
    "Granny Smith": 9,
    "Apple Bloom": 10,
    "Apple family": 11,
    "Rainbow Dash": 12,
    "Rarity": 13,
    "Fluttershy": 14,
    "Ponies": 15,
    "Mayor Mare": 16,
    "Nightmare Moon": 17,
    "Mane Six": 18,
    "Fluttershy, Rainbow Dash, Rarity": 19,
    "Manny Roar": 20,
    "Mane Six except Fluttershy": 21,
    "Steven Magnet": 22,
    "Shadowbolt Leader": 23,
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Rarity": 24,
    "Princess Celestia": 25,
    "Princess Luna": 26,
    "Rainbow Dash, Twilight Sparkle": 27,
    "Applejack, Twilight Sparkle": 28,
    "Applejack, Rainbow Dash": 29,
    "Pinkie Pie, Rarity": 30,
    "Mane Six except Twilight": 31,
    "Savoir Fare": 32,
    "Drizzle": 33,
    "Daisy": 34,
    "Shoeshine": 35,
    "Mane Six except Applejack": 36,
    "Mane Six except Twilight Sparkle": 37,
    "Big McIntosh": 38,
    "Sweetie Drops": 39,
    "Winona": 40,
    "DaisyJo": 41,
    "Mrs Cake": 42,
    "Mr Cake": 43,
    "Nurse Redheart": 44,
    "Mule": 45,
    "Lily Valley": 46,
    "Rose": 47,
    "Pinkie Pie, Rainbow Dash": 48,
    "Gilda": 49,
    "Gilda, Rainbow Dash": 50,
    "Merry May": 51,
    "Pony": 52,
    "Snails": 53,
    "Snips": 54,
    "Trixie": 55,
    "Audience": 56,
    "Snails, Snips": 57,
    "Golden Harvest": 58,
    "Ursa": 59,
    "Snails, Snips, Trixie": 60,
    "Unidentified cow": 61,
    "Applejack, Rainbow Dash, Rarity": 62,
    "Snails, Snips, Spike": 63,
    "Angel": 64,
    "Applejack, Pinkie Pie, Rarity": 65,
    "Razer": 66,
    "Applejack, Rarity": 67,
    "Applejack, Rarity, Twilight": 68,
    "Twilight": 69,
    "Applejack, Fluttershy, Rainbow Dash": 70,
    "Zecora": 71,
    "Applejack, Pinkie Pie, Rainbow Dash, Rarity": 72,
    "Spike, Twilight Sparkle": 73,
    "Fluttershy, Pinkie Pie, Rarity, Twilight Sparkle": 74,
    "Apple Bloom, Zecora": 75,
    "Lotus Blossom": 76,
    "All": 77,
    "Parasprite": 78,
    "Parasprites": 79,
    "Rainbow Dash, Rarity, Twilight Sparkle": 80,
    "Parasprite, Spike": 81,
    "Gardening pony": 82,
    "Applejack, Fluttershy, Rainbow Dash, Rarity": 83,
    "Pinkie Pie, Twilight Sparkle": 84,
    "Hedgehogs": 85,
    "Porcupines": 86,
    "Snakes": 87,
    "Applejack, Spike": 88,
    "Caramel": 89,
    "Rainbowshine": 90,
    "Cheerilee": 91,
    "Diamond Tiara": 92,
    "Twist": 93,
    "Cherilee": 94,
    "Silver Spoon": 95,
    "Diamond Tiara, Silver Spoon": 96,
    "Dr Hooves": 97,
    "Ace Point": 98,
    "Roller ponies": 99,
    "Berryshine": 100,
    "Scootaloo": 101,
    "Sweetie Belle": 102,
    "Tornado Bolt": 103,
    "Piña Colada": 104,
    "Coronet": 105,
    "Opalescence": 106,
    "Applejack, Rainbow Dash, Twilight Sparkle": 107,
    "Mane Six except Rarity": 108,
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash": 109,
    "Hoity Toity": 110,
    "Dumb-Bell": 111,
    "Hoops": 112,
    "Dumb-Bell, Hoops, Score": 113,
    "Score": 114,
    "Applejack, Pinkie Pie, Rarity, Twilight Sparkle": 115,
    "Group": 116,
    "Steam Roller": 117,
    "Foggy Fleece": 118,
    "Madden": 119,
    "Lucy Packard": 120,
    "Meadow Song": 121,
    "Misty Fly": 122,
    "Soarin": 123,
    "Spitfire": 124,
    "Applejack, Pinkie Pie, Twilight Sparkle": 125,
    "Fluttershy, Rarity": 126,
    "Apple Bloom, Scootaloo": 127,
    "Cutie Mark Crusaders": 128,
    "Apple Bloom, Sweetie Belle": 129,
    "Cockatrice": 130,
    "Cutie Mark Crusaders, Fluttershy": 131,
    "Fluttershy, Twilight Sparkle": 132,
    "Frou Frou": 133,
    "Peachy Pie, Sunny Daze": 134,
    "Peachy Pie": 135,
    "Sunny Daze": 136,
    "Sapphire Shores": 137,
    "Rover": 138,
    "Fido": 139,
    "Diamond Dogs": 140,
    "Spot": 141,
    "Sir Spike": 142,
    "Mook dogs": 143,
    "Lady Rarity": 144,
    "Fido, Spot": 145,
    "Mook dog": 146,
    "Photo Finish": 147,
    "Background voice": 148,
    "Lyrica Lilac": 149,
    "Royal Ribbon": 150,
    "Gala Appleby": 151,
    "Lemon Hearts": 152,
    "Fluttershy, Pinkie Pie, Rainbow Dash": 153,
    "Fluttershy, Pinkie Pie, Rainbow Dash, Twilight Sparkle": 154,
    "Little Strongheart": 155,
    "Braeburn": 156,
    "Black Stone": 157,
    "Noteworthy": 158,
    "Morton Saltworthy": 159,
    "Ol' Salt": 160,
    "Buffalo": 161,
    "Chief Thunderhooves": 162,
    "Sheriff Silverstar": 163,
    "Goldengrape": 164,
    "Fluttershy, Rainbow Dash, Rarity, Spike, Twilight Sparkle": 165,
    "Settler ponies": 166,
    "Cherry Berry": 167,
    "Mouse family": 168,
    "Guard 1": 169,
    "Guard 2": 170,
    "Philomena": 171,
    "Guard": 172,
    "Hummingway": 173,
    "Count Caesar": 174,
    "Young Applejack": 175,
    "Aunt Orange": 176,
    "Uncle Orange": 177,
    "Tall Order": 178,
    "Dane Tee Dove": 179,
    "Young Fluttershy": 180,
    "Young Dumb-Bell": 181,
    "Young Hoops": 182,
    "Young Rainbow Dash": 183,
    "Rarity's teacher": 184,
    "Young Rarity": 185,
    "Young Twilight Sparkle": 186,
    "Crystal Clear": 187,
    "Arpeggio": 188,
    "Top Marks": 189,
    "Cherry Fizzy": 190,
    "Igneous Rock Pie": 191,
    "Cloudy Quartz": 192,
    "Young Pinkie Pie": 193,
    "Cutie Mark Crusaders, Mane Six": 194,
    "Owlowiscious": 195,
    "Davenport": 196,
    "Green dragon": 197,
    "Gummy": 198,
    "Pinkie Pie voicing a bucket of turnips": 199,
    "Pinkie Pie voicing a pile of rocks": 200,
    "Pinkie Pie voicing a clump of lint": 201,
    "Pinkie Pie voicing a bag of flour": 202,
    "Pinkie Pie [as Rocky]": 203,
    "Rocky": 204,
    "Sir Lintsalot": 205,
    "Madame le Flour": 206,
    "Mr Turnip": 207,
    "Pinkie Pie [as Mr Turnip]": 208,
    "Pinkie Pie [as Sir Lintsalot]": 209,
    "Pinkie Pie [as Madame le Flour]": 210,
    "Applejack, Fluttershy, Rarity, Twilight Sparkle": 211,
    "Mane Six except Pinkie Pie": 212,
    "Lucky Clover": 213,
    "Prince Blueblood": 214,
    "Mr Greenhooves": 215,
    "Prince Blueblood, Rarity": 216,
    "Joe": 217,
    "Mane Six except Spike": 218,
    "Discord": 219,
    "Rarity, Twilight Sparkle": 220,
    "Apples": 221,
    "Red apples": 222,
    "Light-red apples": 223,
    "Green apples": 224,
    "Pond Rainbow Dash": 225,
    "Pond Fluttershy": 226,
    "Pond Pinkie Pie": 227,
    "Pond Rarity": 228,
    "Pond Twilight Sparkle": 229,
    "Discord, Green apples": 230,
    "Balloons": 231,
    "Butterflies": 232,
    "Flashback Discord": 233,
    "Applejack, Fluttershy, Pinkie Pie, Rarity": 234,
    "Applejack, Fluttershy, Pinkie Pie": 235,
    "Crowd": 236,
    "Fillies": 237,
    "Bear": 238,
    "Apple Bloom, Scootaloo, Sweetie Belle": 239,
    "Orange Swirl": 240,
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Twilight Sparkle": 241,
    "Pipsqueak": 242,
    "Foals": 243,
    "Background ponies": 244,
    "Pinkie Pie, Pipsqueak": 245,
    "Cloud Kicker": 246,
    "Raven": 247,
    "Several ponies": 248,
    "Sassaflash": 249,
    "Citizens": 250,
    "Noi": 251,
    "Princess Luna (as Nightmare Moon)": 252,
    "Hondo Flanks": 253,
    "Cookie Crumbles": 254,
    "Apple Bloom, Applejack": 255,
    "Sheep": 256,
    "Apple Bloom, Applejack, Rarity": 257,
    "Apple Bloom, Applejack, Sweetie Belle": 258,
    "Rarity, Sweetie Belle": 259,
    "Sea Swirl": 260,
    "Scootaloo, Sweetie Belle": 261,
    "Scootaloo, Sweetie Belle, Twist": 262,
    "Apple Bloom, Applejack, Spike": 263,
    "Daisy, Lily Valley, Rose": 264,
    "Fan club": 265,
    "Aura": 266,
    "Millie": 267,
    "Cream Puff": 268,
    "Pony 1": 269,
    "Pony 2": 270,
    "Lemon Daze": 271,
    "Globe Trotter": 272,
    "Wisp": 273,
    "Crafty Crate": 274,
    "Jack Hammer": 275,
    "Jim Beam": 276,
    "Rivet": 277,
    "Amethyst Star": 278,
    "Pine Breeze": 279,
    "Liza Doolots": 280,
    "Mare Do Well": 281,
    "Mane Six except Rainbow Dash": 282,
    "Pinkie Pie, Spike": 283,
    "Others": 284,
    "Bags Valet": 285,
    "Jet Set": 286,
    "Upper Crust": 287,
    "Hayseed Turnip Truck": 288,
    "Jet Set, Upper Crust": 289,
    "Fancy Pants": 290,
    "Fleur de Lis": 291,
    "Announcer": 292,
    "Silver Frames": 293,
    "Golden Gavel": 294,
    "Swan Song": 295,
    "Fancy Pants, Upper Crust": 296,
    "Junebug": 297,
    "Dr Horse": 298,
    "Dr Fauna": 299,
    "Fluttershy, Rainbow Dash": 300,
    "Spike (flashback)": 301,
    "Rarity (flashback)": 302,
    "Rarity, Spike": 303,
    "Pinkie Pie, Rainbow Dash, Rarity": 304,
    "Pegasi": 305,
    "Unicorns": 306,
    "Applejack, Fluttershy, Twilight Sparkle": 307,
    "Applejack, Fluttershy": 308,
    "Apple Bloom, Applejack, Big McIntosh": 309,
    "Filthy Rich": 310,
    "Apple Strudel": 311,
    "Foals except Apple Bloom": 312,
    "Foals, Granny Smith": 313,
    "Pound Cake": 314,
    "Pumpkin Cake": 315,
    "Pound Cake, Pumpkin Cake": 316,
    "Derpy": 317,
    "Conductor": 318,
    "Assembled ponies": 319,
    "Parcel Post": 320,
    "Cherry Jubilee": 321,
    "Coach ponies": 322,
    "Rabbit": 323,
    "Fluttershy, Rainbow Dash, Twilight Sparkle": 324,
    "Flam": 325,
    "Flim": 326,
    "Flam, Flim": 327,
    "Apple Bloom, Big McIntosh, Granny Smith": 328,
    "Apple family, Mane Six": 329,
    "Comet Tail": 330,
    "Pinkie Pie, Rarity, Twilight Sparkle": 331,
    "Doctor Horse": 332,
    "Nurse Sweetheart": 333,
    "Daring Do": 334,
    "Ahuizotl [with Pinkie Pie's voice]": 335,
    "Nurse Snowheart": 336,
    "Ahuizotl": 337,
    "Spider [with Fuzzy Slippers's voice]": 338,
    "Fuzzy Slippers": 339,
    "Screwy": 340,
    "Night Watch": 341,
    "Hay Fever": 342,
    "Persnickety": 343,
    "Big McIntosh, Cheerilee": 344,
    "Karat": 345,
    "Mr Waddle": 346,
    "Matilda": 347,
    "Cranky Doodle Donkey": 348,
    "Cranky Doodle Donkey, Matilda": 349,
    "Sand Trap": 350,
    "Turf": 351,
    "Surf": 352,
    "Gizmo": 353,
    "Roma": 354,
    "Willful Lighting Tech": 355,
    "Willful Stage Manager": 356,
    "Iron Will": 357,
    "Royal Riff": 358,
    "Mr Zippy": 359,
    "Fluttershy, Pinkie Pie, Rarity": 360,
    "Future Twilight Sparkle": 361,
    "Rainbow Dash, Spike": 362,
    "Past Twilight Sparkle": 363,
    "Applejack, Pinkie Pie, Rainbow Dash": 364,
    "Rarity, Spike, Twilight Sparkle": 365,
    "Fume": 366,
    "Clump": 367,
    "Garble": 368,
    "Fizzle": 369,
    "Teenage dragons": 370,
    "Backdraft, Charcoal": 371,
    "Backdraft": 372,
    "Charcoal": 373,
    "Crackle": 374,
    "Rainbow Dash, Rarity, Spike, Twilight Sparkle": 375,
    "Flitter": 376,
    "Film announcer": 377,
    "Thunderlane": 378,
    "Bulk Biceps": 379,
    "Filly Fluttershy": 380,
    "Cloud Chaser": 381,
    "Blossomforth": 382,
    "Cloud Chaser, Flitter": 383,
    "Rumble": 384,
    "Serenity": 385,
    "Slipstream": 386,
    "Young Six": 387,
    "Gallus": 388,
    "Silverstream": 389,
    "Smolder": 390,
    "Yona": 391,
    "Sandbar": 392,
    "Ocellus": 393,
    "Truffle": 394,
    "Ruby Pinch": 395,
    "Green Daze": 396,
    "Cotton Cloudy": 397,
    "Shady Daze": 398,
    "Mr Cake, Mrs Cake": 399,
    "Gustave le Grand": 400,
    "Donut Joe": 401,
    "Mulia Mild": 402,
    "Shining Armor": 403,
    "Young Cadance": 404,
    "Young Cadance, Young Twilight": 405,
    "Young Twilight": 406,
    "Wild Fire": 407,
    "Princess Cadance": 408,
    "Minuette": 409,
    "Lyra Heartstrings": 410,
    "Royal guard": 411,
    "Queen Chrysalis": 412,
    "Princess Cadance, Twilight Sparkle": 413,
    "Lyra Heartstrings, Minuette, Twinkleshine": 414,
    "Changelings": 415,
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Twilight Sparkle": 416,
    "Changelings [as Twilight Sparkle]": 417,
    "Changelings [as Rainbow Dash]": 418,
    "Changeling": 419,
    "Changelings, Queen Chrysalis": 420,
    "Princess Cadance, Shining Armor": 421,
    "Royal guard #1": 422,
    "Royal guard #2": 423,
    "King Sombra": 424,
    "Professor Bill Neigh": 425,
    "Other ponies": 426,
    "Autumn Gem": 427,
    "Fleur De Verre": 428,
    "Elbow Grease": 429,
    "Night Knight": 430,
    "Amethyst Maresbury": 431,
    "Crystal Ponies": 432,
    "Autumn Gem, Fleur De Verre": 433,
    "Crystal Pony": 434,
    "Crystal Beau": 435,
    "Sapphire Joy": 436,
    "Bright Smile": 437,
    "Pinkie Pie 2": 438,
    "Pinkie Pie, Pinkie Pie 2": 439,
    "Pinkie Pie 3": 440,
    "Pinkie Pie 2, Pinkie Pie 3, Pinkie Pie 4": 441,
    "Pinkie Pie 4": 442,
    "Pinkie Pie Duplicates": 443,
    "Pinkie Pie Duplicate": 444,
    "Apple Fritter, Applejack, Big McIntosh, Meadow Song": 445,
    "Apple Fritter": 446,
    "Pinkie Pie Duplicate 2": 447,
    "Pinkie Pie Duplicate 3": 448,
    "Pinkie Pie Duplicate 4": 449,
    "Pinkie Pie Duplicate 5": 450,
    "Pinkie Pie Duplicate 6": 451,
    "Babs Seed": 452,
    "Babs Seed, Diamond Tiara, Silver Spoon": 453,
    "Spectator": 454,
    "Shopkeeper": 455,
    "Rainbow Dash, Snails": 456,
    "Mane Six except Trixie": 457,
    "Baby Snips": 458,
    "Old Snails": 459,
    "Other ponies, Spike": 460,
    "Baby Snails, Baby Snips": 461,
    "Baby Snails": 462,
    "Big McIntosh (as Male Applejack)": 463,
    "Saddle Arabian delegates": 464,
    "Bessie": 465,
    "The Olden Pony": 466,
    "Crocodile": 467,
    "Messenger Pony": 468,
    "All Pegasi": 469,
    "Lightning Dust": 470,
    "Cloudchaser": 471,
    "Meadow Flower": 472,
    "Lightning Dust, Rainbow Dash": 473,
    "Applejack, Fluttershy, Rarity": 474,
    "Fluttershy, Rarity, Twilight": 475,
    "Applejack, Fluttershy, Rarity, Twilight": 476,
    "Young Granny Smith": 477,
    "Half Baked Apple": 478,
    "Apple Split": 479,
    "Baby Applejack": 480,
    "Young Apple Rose": 481,
    "Young Apple Rose, Young Granny Smith": 482,
    "Apple Bloom, Granny Smith": 483,
    "Apple Bloom, Babs Seed": 484,
    "Auntie Applesauce": 485,
    "Apple Rose": 486,
    "Apple Rose, Granny Smith": 487,
    "Apple Dumpling": 488,
    "Apple Leaves": 489,
    "Stallions": 490,
    "Apple Rose, Auntie Applesauce, Granny Smith": 491,
    "Applejack, Granny Smith": 492,
    "Fluttershy, Rainbow Dash, Rarity, Twilight Sparkle": 493,
    "Applejack, Pinkie Pie, Rarity, Spike, Twilight Sparkle": 494,
    "Pinkie Pie, Rarity, Spike, Twilight Sparkle": 495,
    "Tank": 496,
    "Opalesence": 497,
    "Laurette": 498,
    "Train Conductor": 499,
    "Princess Cadance, Twilight": 500,
    "Golden Hooves": 501,
    "Ms. Peachbottom": 502,
    "Ms. Harshwhinny": 503,
    "Athletes": 504,
    "Shining Armor, Twilight Sparkle": 505,
    "Royal guard #3": 506,
    "Royal Guard": 507,
    "Cragadile": 508,
    "Cherry Berry, Comet Tail": 509,
    "Plant Crab": 510,
    "Ahuizotl [with Fluttershy's voice]": 511,
    "A.K. Yearling": 512,
    "Henchponies": 513,
    "Dr Caballeron": 514,
    "Train conductor": 515,
    "Cutie Mark Crusaders, Rainbow Dash": 516,
    "Mane-iac": 517,
    "Henchpony": 518,
    "Luggage Cart": 519,
    "Tourist Pony 1": 520,
    "Businesspony": 521,
    "Pronto": 522,
    "Janine Manewitz": 523,
    "Prim Hemline": 524,
    "Suri Polomare": 525,
    "Coco Pommel": 526,
    "Mane Six except Twilight Sparkle except Rarity": 527,
    "Hinny of the Hills": 528,
    "Applejack, Pinkie Pie": 529,
    "Big McIntosh, Granny Smith": 530,
    "Everypony": 531,
    "Goldie Delicious": 532,
    "Bulk Biceps, Fluttershy": 533,
    "Helia": 534,
    "Mane Moon": 535,
    "Sprinkle Medley": 536,
    "Fleetfoot": 537,
    "Cloudsdale cheerleaders": 538,
    "Rainbowshine, Sprinkle Medley": 539,
    "Fleetfoot, Spitfire": 540,
    "Ponyville team, Wonderbolts": 541,
    "Ponyville team": 542,
    "Wonderbolts": 543,
    "Bulk Biceps, Derpy, Fluttershy": 544,
    "Derpy, Mane Six except Rainbow Dash": 545,
    "Official": 546,
    "Tatzlwurm": 547,
    "Cheese Sandwich": 548,
    "Vendor Pony": 549,
    "Art Vendor": 550,
    "Peachy Pitt": 551,
    "Colt": 552,
    "Cheese Sandwich, Pinkie Pie": 553,
    "Trenderhoof": 554,
    "Animals": 555,
    "Torch Song": 556,
    "The Ponytones": 557,
    "Nightjar": 558,
    "Zipporwhill": 559,
    "Nightjar, Zipporwhill": 560,
    "Mane Six except Fluttershy or Rarity": 561,
    "Seedling": 562,
    "Classmate Pony 2": 563,
    "Classmate Pony 3": 564,
    "Seabreeze": 565,
    "Breezies": 566,
    "Twirly": 567,
    "Breezie": 568,
    "Breezette": 569,
    "Applejack, Big McIntosh, Granny Smith": 570,
    "Apple Bloom, Applejack, Granny Smith": 571,
    "Chimera's tiger head": 572,
    "Chimera's goat head": 573,
    "Chimera's snake head": 574,
    "Chimera": 575,
    "Chimera's goat head, Chimera's tiger head": 576,
    "Duce Switchell": 577,
    "Maud Pie": 578,
    "Sediments": 579,
    "Eclair Crème": 580,
    "Star Gazer": 581,
    "Mint Flower": 582,
    "Little Pony 2": 583,
    "Plum Star": 584,
    "Younger Sweetie Belle": 585,
    "Titania": 586,
    "Backup dancers": 587,
    "Backup dancers, Sapphire Shores": 588,
    "Security guard": 589,
    "Applejack, Big McIntosh": 590,
    "Silver Shill": 591,
    "Jinx": 592,
    "Snappy Scoop": 593,
    "Big McIntosh, Rainbow Dash": 594,
    "Pegasus Stallion #1": 595,
    "Downdraft": 596,
    "Pegasus Stallion #2": 597,
    "High Note": 598,
    "Crowd Pony 1": 599,
    "Crowd Pony 2": 600,
    "Teddie Safari": 601,
    "Cratus": 602,
    "Stellar Eclipse": 603,
    "Match Game": 604,
    "Amethyst Gleam": 605,
    "Crowd Pony 3": 606,
    "Constance": 607,
    "Claude": 608,
    "Mr Robin": 609,
    "Stallion": 610,
    "Crystal Guard": 611,
    "Applejack, Rainbow Dash, Rarity, Twilight Sparkle": 612,
    "Neighls Bohr": 613,
    "Security Guard": 614,
    "Crystal Pony in Crowd": 615,
    "Princess Celestia, Princess Luna": 616,
    "Security Guard 2": 617,
    "Mane Six except Spike, Princess Cadance, Princess Celestia, Princess Luna": 618,
    "Flash Sentry": 619,
    "Duke of Maretonia": 620,
    "Lord Tirek": 621,
    "Rare Find": 622,
    "Princess Cadance, Princess Luna, Twilight Sparkle": 623,
    "Sunny Song": 624,
    "Town pony #1": 625,
    "Town pony #2": 626,
    "Bacon Braids": 627,
    "Town pony #3": 628,
    "Offbeat": 629,
    "Cotton Cloudy, Princess Erroria, Ruby Pinch, Town pony #4": 630,
    "Princess Erroria": 631,
    "Town pony #4": 632,
    "Night Glider": 633,
    "Party Favor": 634,
    "Double Diamond": 635,
    "Starlight Glimmer": 636,
    "Ivy Vine": 637,
    "Burlap": 638,
    "Sugar Belle": 639,
    "Rosemary": 640,
    "Rocky Storm": 641,
    "Aloe": 642,
    "Rainbow Dash, Rarity": 643,
    "Mane Six except Applejack except Twilight": 644,
    "Pest Control Pony": 645,
    "Mysterious Voice": 646,
    "Sunshower": 647,
    "Open Skies": 648,
    "Clear Skies": 649,
    "Clear Skies, Open Skies": 650,
    "Parasol": 651,
    "Fluttershy, Pinkie Pie, Rainbow Dash, Rarity": 652,
    "Townspony 1": 653,
    "Townspony 2": 654,
    "Townspony 3": 655,
    "Townspony 4": 656,
    "Star Spur": 657,
    "Senior Deputy": 658,
    "Trouble Shoes": 659,
    "Young Trouble Shoes": 660,
    "Judges": 661,
    "Female Townspony #1": 662,
    "Male Townspony #1": 663,
    "Female Townspony #2": 664,
    "Judge": 665,
    "Tree Hugger": 666,
    "The Smooze": 667,
    "Apple Bloom, Applejack, Fluttershy, Rainbow Dash, Scootaloo, Tree Hugger": 668,
    "S01E26 Unnamed Earth Mare #1": 669,
    "Grampa Gruff": 670,
    "Arimaspi": 671,
    "Storekeeper": 672,
    "Greta": 673,
    "Young Gilda": 674,
    "Young Gilda, Young Rainbow Dash": 675,
    "Gilda, Pinkie Pie, Rainbow Dash": 676,
    "Jeff Letrotski": 677,
    "Octavia Melody": 678,
    "Walter": 679,
    "Neigh Sayer": 680,
    "Delegate 2": 681,
    "Polo ponies": 682,
    "Horticultural Pegasus": 683,
    "Public Works Pony": 684,
    "Joe Pescolt, March Gustysnows": 685,
    "Joe Pescolt": 686,
    "March Gustysnows": 687,
    "Annoyed Delegate": 688,
    "Fluffy Clouds": 689,
    "Frazzle Rock": 690,
    "Princess Cadance, Spike": 691,
    "Prince Rutherford": 692,
    "Prince Rutherford, Yaks": 693,
    "Yaks": 694,
    "Mane Six except Pinkie": 695,
    "Monster": 696,
    "Mane Six, Princess Celestia, Yaks": 697,
    "Lemon Hearts, Minuette, Twilight Sparkle, Twinkleshine": 698,
    "Lemon Hearts, Minuette, Twinkleshine": 699,
    "Minuette, Twinkleshine": 700,
    "Young Moon Dancer": 701,
    "Moon Dancer": 702,
    "Lemon Hearts, Twinkleshine": 703,
    "Minuette, Spike, Twilight Sparkle, Twinkleshine": 704,
    "Lemon Hearts, Minuette, Moon Dancer, Twinkleshine": 705,
    "Giant Evil Angel": 706,
    "Sunflowers": 707,
    "Sassy Saddles": 708,
    "Fashion Plate": 709,
    "Fashion Plate, Rarity": 710,
    "Mane Six except Rarity, Twilight": 711,
    "Cayenne": 712,
    "Pretzel": 713,
    "Moonlight Raven": 714,
    "Sunshine Smiles": 715,
    "North Point": 716,
    "Citrus Blush": 717,
    "Whoa Nelly": 718,
    "Rarity, Sassy Saddles": 719,
    "Package Deal": 720,
    "Wind Rider": 721,
    "Stormy Flare": 722,
    "Blaze": 723,
    "Castle Guard 1": 724,
    "Spearhead": 725,
    "Cinnamon Chai": 726,
    "Diamond Cutter": 727,
    "Strawberry Ice": 728,
    "Pedestrian Ponies 3 & 4": 729,
    "Pearmain Worcester": 730,
    "Stinky Bottom": 731,
    "Street Pony": 732,
    "Fine Print": 733,
    "Chock-full Carafe": 734,
    "Uptown Clover": 735,
    "On Stage": 736,
    "Raspberry Beret": 737,
    "Late Show": 738,
    "Cloudy Daze": 739,
    "Blueberry Curls": 740,
    "Stardom": 741,
    "Luckette": 742,
    "Pearly Stitch": 743,
    "Viola": 744,
    "Booth Barker": 745,
    "Apple Bloom, Big McIntosh": 746,
    "Rainbow Dash, Scootaloo": 747,
    "Registration Pony": 748,
    "Spoiled Rich": 749,
    "Cheerilee, Foals": 750,
    "Mrs Cake, Pumpkin Cake": 751,
    "Featherweight": 752,
    "Wooden Legs": 753,
    "Mane Six except Pinkie Pie, Shining Armor": 754,
    "Porter Pony": 755,
    "Igneous Rock": 756,
    "Limestone Pie": 757,
    "Marble Pie": 758,
    "Pie family": 759,
    "Apple family, Pie family": 760,
    "Harry": 761,
    "Amethyst Star, Twinkleshine": 762,
    "Mane Six except Fluttershy, Pinkie Pie": 763,
    "Flutterbat": 764,
    "Discord, Rainbow Dash": 765,
    "Discord, Fluttershy, Rarity": 766,
    "Discord, Mane Six except Twilight Sparkle": 767,
    "Discord, Mane Six": 768,
    "Ma Hooffield": 769,
    "Buzzard Hooffield": 770,
    "Mice": 771,
    "Steel Bolts": 772,
    "Rosy Riveter": 773,
    "Big Daddy McColt": 774,
    "McColts": 775,
    "McColt Guards": 776,
    "Hacksaw McColt": 777,
    "Hooffields": 778,
    "Big Daddy McColt, Ma Hooffield": 779,
    "Lyra Heartstrings, Sweetie Drops": 780,
    "Fluttershy, Noteworthy, Rainbow Dash, Rarity, Royal Riff, Spike, Sprinkle Medley, Twilight Sparkle": 781,
    "Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Royal Riff, Spike, Sprinkle Medley, Twilight Sparkle": 782,
    "Svengallop": 783,
    "Coloratura": 784,
    "Audience Pony": 785,
    "Hoops, Young Dumb-Bell": 786,
    "Fluttershy, Hoops, Young Dumb-Bell": 787,
    "Starlight Glimmer, Twilight Sparkle": 788,
    "Sunburst": 789,
    "Scarlet Heart": 790,
    "Amber Laurel": 791,
    "Golden Väs": 792,
    "Flurry Heart": 793,
    "Cloudy Spinel": 794,
    "Coral Shores": 795,
    "Tough Nut": 796,
    "Scouts Honor": 797,
    "Mustafa Combe": 798,
    "Spike, Starlight Glimmer": 799,
    "Night Light": 800,
    "Twilight Velvet": 801,
    "Deputy Copper": 802,
    "Street Rat": 803,
    "Hoofer Steps": 804,
    "Tender Taps": 805,
    "Dragon Lord Torch": 806,
    "Dragons": 807,
    "Princess Ember": 808,
    "Maar": 809,
    "Barry": 810,
    "Cherry Berry, Goldengrape": 811,
    "Caramel, Shoeshine, Sunshower Raindrops": 812,
    "Sunshower Raindrops": 813,
    "Starlight Glimmer, Trixie": 814,
    "Rainbow Dash, Spitfire": 815,
    "Young Hoops, Young Pegasi": 816,
    "Young Pegasi": 817,
    "Fleetfoot, High Winds, Misty Fly, Soarin, Surprise": 818,
    "High Winds": 819,
    "Surprise": 820,
    "Rainbow Dash, Surprise": 821,
    "Cutie Mark Crusaders, Mane Six except Rainbow Dash": 822,
    "Professor Flintheart": 823,
    "Young Starlight Glimmer": 824,
    "Buried Lede": 825,
    "Mr Stripes": 826,
    "Plaid Stripes": 827,
    "Rarity Devil": 828,
    "Rarity Angel": 829,
    "Dancers": 830,
    "Blue Bobbin": 831,
    "Waxton": 832,
    "Lavender Essence": 833,
    "Buddy": 834,
    "Birch Bucket": 835,
    "Mrs Shy": 836,
    "Mr Shy": 837,
    "Zephyr Breeze": 838,
    "Saffron Masala": 839,
    "Coriander Cumin": 840,
    "Chargrill Breadwinner": 841,
    "Orange Slice": 842,
    "Pinkie Pie, Saffron Masala": 843,
    "Zesty Gourmand": 844,
    "Coriander Cumin, Pinkie Pie, Rarity": 845,
    "Coriander Cumin, Saffron Masala": 846,
    "Coriander Cumin, Pinkie Pie": 847,
    "Sweet Biscuit": 848,
    "Burly Unicorn": 849,
    "Matronly Pony": 850,
    "Salespony": 851,
    "Quibble Pants, Rainbow Dash": 852,
    "Quibble Pants": 853,
    "A. K. Yearling": 854,
    "Pickpocket": 855,
    "Cipactli": 856,
    "Dr Caballeron, Henchponies": 857,
    "Upper class ponies": 858,
    "Mrs Cake, Pinkie Pie": 859,
    "Lyra Heartstrings, Twinkleshine": 860,
    "Zombie ponies": 861,
    "Honeysparkle": 862,
    "Royal guard 1": 863,
    "Royal guard 2": 864,
    "Thorax": 865,
    "Baby Thorax": 866,
    "Spike, Thorax": 867,
    "Royal guards, Shining Armor": 868,
    "Princess Cadance, Sunburst": 869,
    "Opposite Fluttershy": 870,
    "Mini-Discord": 871,
    "Big McIntosh, Spike": 872,
    "Squizard": 873,
    "Big McIntosh, Discord, Spike": 874,
    "Discord, Spike": 875,
    "Crimson Heart": 876,
    "Aloha": 877,
    "Fluttershy, Pinkie Pie": 878,
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Snails": 879,
    "Mrs Paleo": 880,
    "Mr Paleo": 881,
    "Petunia Paleo": 882,
    "Mr Paleo, Mrs Paleo": 883,
    "Gabby": 884,
    "Elderly griffon": 885,
    "Barker": 886,
    "Gladmane": 887,
    "Trapeze Star": 888,
    "Director": 889,
    "Roar Horn": 890,
    "Sprigfield": 891,
    "Bernard Rabbit": 892,
    "Back Stage": 893,
    "Roar Horn, Sprigfield": 894,
    "Young Big McIntosh": 895,
    "Young Applejack, Young Big McIntosh": 896,
    "Spoiled Milk": 897,
    "Granny Smith, Young Applejack": 898,
    "Granny Smith, Young Big McIntosh": 899,
    "Hippocratic Oath": 900,
    "Doctor Spring Bud": 901,
    "Open Heart": 902,
    "Angel Wings": 903,
    "Sky Stinger": 904,
    "Recruits except Sky Stinger": 905,
    "Vapor Trail": 906,
    "Recruits": 907,
    "Twirly Whirly": 908,
    "Steer Straight": 909,
    "Young Vapor Trail": 910,
    "Young Sky Stinger": 911,
    "Double Diamond, Party Favor": 912,
    "Village ponies": 913,
    "Princess Luna, Starlight Glimmer": 914,
    "Changeling Twilight": 915,
    "Pigasus": 916,
    "Thorax, Trixie": 917,
    "Fluttershys": 918,
    "Fluttershy #1": 919,
    "Fluttershy #2": 920,
    "Fluttershy #3": 921,
    "Fluttershy #4": 922,
    "Starlight Glimmer, Thorax": 923,
    "Changeling Girl": 924,
    "Changeling 1": 925,
    "Goofy Changeling": 926,
    "Cornicle": 927,
    "Princess Ember, Starlight Glimmer": 928,
    "Sunburst, Twilight Sparkle": 929,
    "Ginger Locks": 930,
    "Clarity Cut": 931,
    "Cake Twins, Flurry Heart": 932,
    "Cake Twins": 933,
    "Foals, Nurse Redheart": 934,
    "Flurry Heart, Twilight Sparkle": 935,
    "Peach Fuzz": 936,
    "Rusty Tenure": 937,
    "Clementine": 938,
    "Dr Fauna, Fluttershy": 939,
    "Rupert": 940,
    "Dandy Grandeur": 941,
    "Wrangler": 942,
    "Hard Hat": 943,
    "Dandy Grandeur, Hard Hat, Wrangler": 944,
    "Jack Hammer, Steam Roller": 945,
    "Starry Eyes": 946,
    "Chipcutter": 947,
    "Ripley": 948,
    "Apple Bloom, Scootaloo, Zipporwhill": 949,
    "Bow Hothoof": 950,
    "Windy Whistles": 951,
    "Bow Hothoof, Windy Whistles": 952,
    "Bow Hothoof, Rainbow Dash, Windy Whistles": 953,
    "Feather Bangs": 954,
    "Swooning Ponies": 955,
    "Swoon Song": 956,
    "Fond Feather": 957,
    "Big McIntosh, Sugar Belle": 958,
    "Inky Rose, Lily Lace, Starstreak": 959,
    "Inky Rose": 960,
    "Lily Lace": 961,
    "Starstreak": 962,
    "Hoity Toity, Photo Finish": 963,
    "Hoity Toity, Lily Lace, Rarity": 964,
    "All except Applejack": 965,
    "Strawberry Sunrise": 966,
    "Hard Hat, Jack Hammer, Rivet, Steam Roller": 967,
    "Delegate Ponies": 968,
    "Mayor Cream Cheese": 969,
    "Mayor Baltimare": 970,
    "Mayor Baltimare, Mayor Cream Cheese": 971,
    "Pancakes": 972,
    "Daybreaker": 973,
    "Princess Celestia, Starlight Glimmer": 974,
    "Dream Ponies": 975,
    "Dream Pony": 976,
    "Pinkie Pie, Prince Rutherford, Yaks": 977,
    "Pinkie Pie, Yaks": 978,
    "Yak Kid 1": 979,
    "Yak Kid 2": 980,
    "Prince Rutherford, Yak": 981,
    "Yak": 982,
    "Discord, Fluttershy": 983,
    "Discord's finger": 984,
    "Discord 2": 985,
    "Jasmine Leaf": 986,
    "Raspberry Vinaigrette": 987,
    "Piñata": 988,
    "Discord 3": 989,
    "Other Discords": 990,
    "All Discords": 991,
    "Grand Pear": 992,
    "Young Grand Pear": 993,
    "Young Bright Macintosh": 994,
    "Young Pear Butter": 995,
    "Burnt Oak": 996,
    "Bright Mac": 997,
    "Pear Butter": 998,
    "Bright Mac, Pear Butter": 999,
    "Chiffon Swirl": 1000,
    "Young Mayor Mare": 1001,
    "Grand Pear, Granny Smith": 1002,
    "Toola Roola": 1003,
    "Coconut Cream": 1004,
    "Coconut Cream, Toola Roola": 1005,
    "Out of Town Pony": 1006,
    "Out of Town Pony 2": 1007,
    "Lavender Bloom": 1008,
    "Pegasus Fillies": 1009,
    "Glasses Stallion": 1010,
    "Lemon Chiffon": 1011,
    "Sweet Apple Admirer": 1012,
    "Reporter Pony": 1013,
    "Ember": 1014,
    "Crusoe Palm": 1015,
    "Rainbow Stars": 1016,
    "Crusoe Palm, Rainbow Stars": 1017,
    "Ember, Thorax": 1018,
    "Spike, Starlight Glimmer, Twilight Sparkle": 1019,
    "Ember, Spike, Thorax": 1020,
    "Mighty Helm ponies": 1021,
    "Rockhoof": 1022,
    "Rainbow Dash, Scootaloo, Sweetie Belle": 1023,
    "All except Rainbow Dash": 1024,
    "All except Sweetie Belle": 1025,
    "Mistmane": 1026,
    "Villager": 1027,
    "Foal": 1028,
    "Sable Spirit": 1029,
    "Flash Magnus": 1030,
    "Commander Ironhead": 1031,
    "Pharynx": 1032,
    "Sclerite": 1033,
    "Frenulum": 1034,
    "Green Changeling": 1035,
    "Tymbal": 1036,
    "Changeling 2": 1037,
    "Changeling 3": 1038,
    "All changelings": 1039,
    "Pharnyx": 1040,
    "Young Changeling": 1041,
    "Young Pharynx": 1042,
    "Young Thorax": 1043,
    "Passing Changeling": 1044,
    "Newspaper Pony": 1045,
    "Cortland": 1046,
    "Mrs Trotsworth": 1047,
    "Random Villager": 1048,
    "Nile Faras": 1049,
    "Mr Breezy": 1050,
    "Chelsea Porcelain": 1051,
    "Creature": 1052,
    "Customer Pony": 1053,
    "Silver Medal": 1054,
    "Mane Six except Rarity, Starlight Glimmer": 1055,
    "Daisy, Lily Valley": 1056,
    "Cattail": 1057,
    "Fluttershy, Mage Meadowbrook": 1058,
    "Mage Meadowbrook": 1059,
    "Chipmunk": 1060,
    "Meadowbrook's Mother": 1061,
    "Royal Pin": 1062,
    "Kettle Corn": 1063,
    "Skeedaddle": 1064,
    "Sparkle family": 1065,
    "Sparkle family except Twilight Sparkle": 1066,
    "Night Light, Twilight Velvet": 1067,
    "Raspberry Sorbet": 1068,
    "Cruise Ponies": 1069,
    "Sunny Side": 1070,
    "Star Tracker": 1071,
    "Sun Cloche": 1072,
    "Cruise ponies": 1073,
    "Fan": 1074,
    "Flurry Heart, Princess Cadance": 1075,
    "Everypony else": 1076,
    "Cruise pony": 1077,
    "Janitor Pony": 1078,
    "Fleetfoot, Soarin, Spitfire": 1079,
    "EMT Pony": 1080,
    "All Aboard": 1081,
    "Young Sunburst": 1082,
    "All except Maud Pie": 1083,
    "Star Swirl the Bearded": 1084,
    "Pony of Shadows": 1085,
    "Professor Fossil": 1086,
    "Lotus Petal": 1087,
    "Billy": 1088,
    "Dragon": 1089,
    "Fahal Alkhayl": 1090,
    "Somnambula": 1091,
    "Sirens": 1092,
    "Aria Blaze": 1093,
    "Stygian": 1094,
    "Neighsay": 1095,
    "Seaspray": 1096,
    "Gallus, Yona": 1097,
    "Ocellus, Silverstream, Yona": 1098,
    "Silverstream, Smolder": 1099,
    "Ember, Grampa Gruff, Prince Rutherford, Seaspray, Thorax": 1100,
    "Sandbar, Smolder": 1101,
    "Young Six except Silverstream": 1102,
    "Mudbriar": 1103,
    "Fluttershy's apparition": 1104,
    "Rarity's apparition": 1105,
    "Applejack's apparition": 1106,
    "Rainbow Dash's apparition": 1107,
    "Twilight Sparkle's apparition": 1108,
    "Mane five's apparitions": 1109,
    "Background pony 1": 1110,
    "Background pony 2": 1111,
    "Background pony 3": 1112,
    "Background pony 4": 1113,
    "Pursey Pink": 1114,
    "Pursey Pink, Rarity": 1115,
    "Bracer Britches": 1116,
    "Silver Berry": 1117,
    "Old Money": 1118,
    "Valley Trend": 1119,
    "Snow Hope": 1120,
    "Joan Pommelway": 1121,
    "Mare E. Lynn": 1122,
    "Applejack, Pinkie Pie, Rainbow Dash, Spike, Twilight Sparkle": 1123,
    "Applejack, Pinkie Pie, Rainbow Dash, Twilight Sparkle": 1124,
    "Grannies": 1125,
    "Applejack vision": 1126,
    "Cranberry Muffin": 1127,
    "Tight End": 1128,
    "Carnival Barker": 1129,
    "Jack Pot": 1130,
    "Big Bucks": 1131,
    "Terramar": 1132,
    "Sky Beak": 1133,
    "Cutie Mark Crusaders, Twilight Sparkle": 1134,
    "Ocean Flow": 1135,
    "Applejack, Fluttershy, Rainbow Dash, Rarity, Starlight Glimmer": 1136,
    "All except Pinkie Pie": 1137,
    "All except Twilight Sparkle": 1138,
    "Mail Pony": 1139,
    "Starlight Glimmer, Sunburst, Twilight Sparkle": 1140,
    "Automated voice": 1141,
    "Ever Essence": 1142,
    "Raspberry Latte": 1143,
    "Minty Mocha": 1144,
    "Firelight": 1145,
    "Stellar Flare": 1146,
    "Firelight, Stellar Flare": 1147,
    "Starlight Glimmer, Sunburst": 1148,
    "Cracked Wheat": 1149,
    "Ever Essence, Minty Mocha, Raspberry Latte": 1150,
    "Young Six except Sandbar": 1151,
    "Gallus, Smolder": 1152,
    "Peewee": 1153,
    "Tourist Pony": 1154,
    "Citrine Spark": 1155,
    "Berry Bliss": 1156,
    "Cozy Glow": 1157,
    "Apple Bloom, Cozy Glow": 1158,
    "Cozy Glow, Cutie Mark Crusaders": 1159,
    "Photographer": 1160,
    "Mean Pinkie Pie": 1161,
    "Mean Fluttershy": 1162,
    "Mean Rarity": 1163,
    "Mean Applejack": 1164,
    "Mean Rainbow Dash": 1165,
    "Mean Twilight Sparkle": 1166,
    "Bird 1": 1167,
    "Bird 2": 1168,
    "Applejack, Rainbow Dash, Rarity, Starlight Glimmer": 1169,
    "Mean Applejack, Mean Pinkie Pie, Mean Rarity": 1170,
    "Rarity, Starlight Glimmer": 1171,
    "Mane Six except Twilight Sparkle or Fluttershy": 1172,
    "Mean Ponies": 1173,
    "Mean Fluttershy, Mean Rarity": 1174,
    "Applejack, Starlight Glimmer": 1175,
    "Voice on bananaphone": 1176,
    "Ocellus, Smolder": 1177,
    "King Grover Painting": 1178,
    "Gallus, Silverstream": 1179,
    "Changeling Painting": 1180,
    "Pony Painting": 1181,
    "Discord's Ghost": 1182,
    "Rainbow Dash, Spike, Twilight Sparkle": 1183,
    "Young Six except Yona": 1184,
    "Young Six except Gallus": 1185,
    "Polo Play": 1186,
    "Chancellor Neighsay": 1187,
    "Destitute Pony": 1188,
    "Student 4": 1189,
    "Cherry Fizzy, Lyra Heartstrings, Rose, Savoir Fare, Sweetie Drops": 1190,
    "Bufogren": 1191,
    "Yak waiter": 1192,
    "Yigrid": 1193,
    "Hoo'Far": 1194,
    "Tall Pony": 1195,
    "Short Pony": 1196,
    "Round Pony": 1197,
    "Rainy Day": 1198,
    "Snow Violet": 1199,
    "Rainy Day, Snow Violet": 1200,
    "Announcer, Crowd": 1201,
    "Fanpony": 1202,
    "Rolling Thunder, Short Fuse": 1203,
    "Rolling Thunder": 1204,
    "Short Fuse": 1205,
    "Gallus, Silverstream, Yona": 1206,
    "Hippogriff Sailor": 1207,
    "Ocellus, Sandbar": 1208,
    "Young Six except Smolder": 1209,
    "Young Six except Ocellus": 1210,
    "Illusion Twilight Sparkle": 1211,
    "Stepford Pony 1": 1212,
    "Stepford Pony 2": 1213,
    "Illusion Rarity": 1214,
    "Illusion Rainbow Dash": 1215,
    "Spindle": 1216,
    "Tree of Harmony": 1217,
    "Silverstream, Yona": 1218,
    "Loose Tracks": 1219,
    "Autumn Blaze": 1220,
    "Rain Shine": 1221,
    "Sludge": 1222,
    "Mane Six, Spike": 1223,
    "Sludge, Spike": 1224,
    "Special Delivery": 1225,
    "Patty Peppermint": 1226,
    "Cerberus": 1227,
    "Cutie Mark Crusaders, Sandbar": 1228,
    "Chancellor Neighsay, Twilight Sparkle": 1229,
    "All except Cutie Mark Crusaders": 1230,
    "Grogar": 1231,
    "Lord Tirek, Queen Chrysalis": 1232,
    "Mane Six except Twilight Sparkle, Starlight Glimmer": 1233,
    "Mane Six except Twilight Sparkle, Spike": 1234,
    "Star Swirl": 1235,
    "Mane Six, Princess Celestia, Princess Luna": 1236,
    "Cozy Glow, Lord Tirek, Queen Chrysalis": 1237,
    "Tourists": 1238,
    "Server Pony": 1239,
    "Saturn": 1240,
    "BeauDe Mane": 1241,
    "Dusty Pages": 1242,
    "Librarian Pony": 1243,
    "First Folio": 1244,
    "Meathead Pony": 1245,
    "Old Stallion": 1246,
    "Dusty Pages, Spike": 1247,
    "Male Pony": 1248,
    "Clear Sky": 1249,
    "Wind Sprint": 1250,
    "Game Announcer": 1251,
    "Referee": 1252,
    "Clear Sky, Quibble Pants, Wind Sprint": 1253,
    "Gallus, Ocellus, Smolder": 1254,
    "Gallus, Ocellus, Silverstream, Smolder": 1255,
    "Sandbar, Yona": 1256,
    "Rusty Bucket": 1257,
    "Cozy Glow, Lord Tirek": 1258,
    "Cozy Glow, Queen Chrysalis": 1259,
    "Fluttershy, Smolder, Spike": 1260,
    "Dragons, Garble": 1261,
    "Billy, Clump, Fume": 1262,
    "Goldie Delicious, Granny Smith": 1263,
    "Student Pony": 1264,
    "Sunburst, Trixie": 1265,
    "Sunburst, Terramar, Trixie": 1266,
    "Edith": 1267,
    "Aunt Holiday": 1268,
    "Auntie Lofty": 1269,
    "Snap Shutter": 1270,
    "Mane Allgood": 1271,
    "Mr Tortoise-Snap": 1272,
    "Guard Pony 1": 1273,
    "Guard Pony 2": 1274,
    "Sans Smirk": 1275,
    "Factory Pony": 1276,
    "Lighthoof, Shimmy Shake": 1277,
    "Lighthoof": 1278,
    "Shimmy Shake": 1279,
    "Cheer Squad": 1280,
    "Pizzelle": 1281,
    "November Rain": 1282,
    "Ocellus, Yona": 1283,
    "School of Friendship Team": 1284,
    "Apple Honey": 1285,
    "Apple Cobbler": 1286,
    "Feather Flatterfly": 1287,
    "Fire Flare": 1288,
    "Unicorn 1": 1289,
    "Antoine": 1290,
    "Muriel": 1291,
    "Sandra": 1292,
    "Scout": 1293,
    "Gabby, Spike": 1294,
    "Pinkie Pie, Rarity, Spike": 1295,
    "All except Starlight Glimmer": 1296,
    "Dad Changeling": 1297,
    "Yona's Parents": 1298,
    "Groom Q. Q. Martingale": 1299,
    "Rogue": 1300,
    "Dr Caballeron, Fluttershy, Henchponies": 1301,
    "Withers": 1302,
    "Biff": 1303,
    "Daring Do, Dr Caballeron": 1304,
    "Spur": 1305,
    "Biscuit": 1306,
    "Savage Honeydew, Spring Green": 1307,
    "Savage Honeydew": 1308,
    "Spring Green": 1309,
    "Bloofy": 1310,
    "Passerby Pony": 1311,
    "Talking Apple": 1312,
    "Talking Apple 2": 1313,
    "Talking Apple 3": 1314,
    "Cutie Mark Crusaders, Granny Smith": 1315,
    "Giant Apple": 1316,
    "Large Apple": 1317,
    "Unicorn Baker": 1318,
    "Fruit Seller": 1319,
    "Pillars": 1320,
    "Queen Chrysalis, Starlight Glimmer": 1321,
    "Royal Guards": 1322,
    "Princess Celestia, Princess Luna, Twilight Sparkle": 1323,
    "Winter Lotus": 1324,
    "S08E14 Unnamed Earth Mare #4": 1325,
    "Earth Pony 2": 1326,
    "Cotton Sky": 1327,
    "Hyper Sonic": 1328,
    "Rasberry[sic] Dazzle": 1329,
    "Future Spike": 1330,
    "Future Gallus": 1331,
    "Luster Dawn": 1332,
    "Baker Pony": 1333,
    "Future Pinkie Pie": 1334,
    "Future Rarity": 1335,
    "Future Rainbow Dash": 1336,
    "Future Applejack": 1337,
    "Future Fluttershy": 1338,
    "Future Mane Six, Spike": 1339,
    "Future Mane Six": 1340,
    "Mane Six, Spike, Starlight Glimmer": 1341
}

async function writeTranscript() {
    const outputFile = Bun.file("./transcript.txt")
    const writer = outputFile.writer()

    let episodeID = 101
    let currentSpeaker = 0
    let speakerID = "000"
    console.clear()
    await streamAndIterate("./raw.txt", line => {
        line = line.trim()
        let episode = titleMap?.[line]
        if (episode) {
            episodeID = episode
            console.log(`Episode ${episodeID} ${line.trim()}`)
        } else {
            let text = ""
            if (line[0] === "[") {
                // Stage Direction
                text = line.trim();

                currentSpeaker = speakers?.[text.slice(1, -1)] || 0;
                speakerID = currentSpeaker.toString(16).padStart(3, "0")
            } else {
                if (line.match(":")) {
                    // New Dialogue
                    let speaker = line.replace(/\:.*/, "").trim();
                    if (speaker.match(/,| and /)) {
                        speaker = speaker
                            .replace(/ and/g, ",")
                            .replace(/,,/g, ",") // Standardise commas
                            .split(/, /)
                            .map(s => s.trim())
                            .filter(s => s.length > 0)
                            .sort() // Sort alphabetically to prevent duplicates
                            .join(", ")
                    }
                    currentSpeaker = speakers?.[speaker] || 0;
                    if (!currentSpeaker) console.warn(`Unknown Speaker ${speaker}`)
                    speakerID = currentSpeaker.toString(16).padStart(3, "0");

                    text = line.replace(/^[^:]*: /, "").trim();
                } else {
                    // Continued Dialogue
                    text = line.trim();
                }
            }
            writer.write(`${episodeID}${speakerID} ${text}\n`);
        }
    })
    writer.end()
    console.log("Finished writing transcript file")
}

async function getSpeakers() {
    let speakers = {}
    let speakersLength = 0
    const baseGroups = {
        "Mane Six": ["Twilight Sparkle", "Pinkie Pie", "Applejack", "Rainbow Dash", "Rarity", "Fluttershy"],
        "Cutie Mark Crusaders": ["Apple Bloom", "Sweetie Belle", "Scootaloo"],
        "Foals": [],
        "Recruits": ["Angel Wings", "Sky Stinger", "Vapor Trail"],
        "Sparkle family": ["Night Light", "Twilight Velvet"],
        "Young Six": ["Gallus", "Silverstream", "Smolder", "Yona", "Sandbar", "Ocellus"],
        "All": [],
        "All Discords": ["Discord", "Discord 2", "Discord 3"],
        "All changelings": ["Changeling 1", "Changeling 2", "Changeling 3", "Green Changeling", "Pharnyx", "Tymbal"],
        "All Pegasi": ["Cloud Chaser", "Rainbow Dash", "Lightning Dust"]
    }
    let speakerGroups = {}

    function addSpeaker(speaker) {
        if (/,| and /.test(speaker)) {
            speaker = speaker
                .replace(/ and/g, ",").replace(/,,/g, ",") // Standardise oxford commas
                .split(", ")
                .map(s => s.trim())
                .filter(s => s.length > 0)
                .sort() // Sort alphabetically to prevent duplicates
                .join(", ")
        }

        let hit = speakers[speaker]
        if (hit) return
        speakers[speaker] = ++speakersLength

        if (/, /.test(speaker)) {
            let all = speaker.split(", ")
            all.forEach(addSpeaker)

            let id = speakers[speaker].toString(16)
            hit = speakerGroups[id]
            if (!hit) speakerGroups[id] = all.map(name => speakers[name])

        }

        if (baseGroups[speaker]) {
            let groupMembers = baseGroups[speaker]
            groupMembers.forEach(addSpeaker)

            let id = speakers?.[speaker].toString(16)
            let hit = speakerGroups[id]
            if (!hit) speakerGroups[id] = groupMembers.map(name => speakers[name])
        }

        if (/except/.test(speaker)) {
            let [group, exclusions] = speaker.split(" except ")
            exclusions = exclusions.split(" or ").map(s => s.trim()).filter(s => s.length > 0).sort()

            if (!baseGroups[group]) console.log(`Unknown group ${group}`)
            else {
                let groupMembers = baseGroups[group].filter(member => !exclusions.includes(member))
                groupMembers.forEach(addSpeaker)

                if (!speakers?.[group]) addSpeaker(group)
                let id = speakers[group].toString(16)
                let hit = speakerGroups[id]
                if (!hit) speakerGroups[id] = groupMembers.map(name => speakers[name])
            }
        }
    }

    let episodeID = 101
    console.clear()
    await streamAndIterate("./raw.txt", line => {
        line = line.trim()
        let episode = titleMap?.[line]
        if (episode) {
            episodeID = episode
            console.log(`Episode ${episodeID} ${line.trim()}`)
        } else {
            let text = ""
            if (line[0] === "[") {
                text = line.slice(1, -1).trim(); // Check for speaking in square brackets
            } else {
                if (line.match(":")) {
                    // New Dialogue
                    addSpeaker(line.replace(/\:.*/, "").trim())
                }
            }
        }
    })
    await Bun.write("./speakers.json", JSON.stringify(speakers, null, 4));
    await Bun.write("./speakers-arr.json", JSON.stringify(["Unknown"].concat(Object.keys(speakers)), null, 4));
    await Bun.write("./speakerGroups.json", JSON.stringify(speakerGroups, null, 4));
    console.log("Finished writing speakers file")
}

await getSpeakers()
// await writeTranscript()