import { readLines } from "https://deno.land/std@0.224.0/io/mod.ts"; // Deno only
const speakers = [
    "Unknown",
    "Narrator",
    "Narrator, Twilight Sparkle",
    "Twilight Sparkle",
    "Twinkleshine",
    "Spike",
    "Royal guards",
    "Pinkie Pie",
    "Applejack",
    "Granny Smith",
    "Apple Bloom",
    "Apple family",
    "Rainbow Dash",
    "Rarity",
    "Fluttershy",
    "Ponies",
    "Mayor Mare",
    "Nightmare Moon",
    "Mane Six",
    "Fluttershy, Rainbow Dash, Rarity",
    "Manny Roar",
    "Mane Six except Fluttershy",
    "Steven Magnet",
    "Shadowbolt Leader",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Rarity",
    "Princess Celestia",
    "Princess Luna",
    "Rainbow Dash, Twilight Sparkle",
    "Applejack, Twilight Sparkle",
    "Applejack, Rainbow Dash",
    "Pinkie Pie, Rarity",
    "Mane six except Twilight",
    "Savoir Fare",
    "Drizzle",
    "Daisy",
    "Shoeshine",
    "Rest of mane six",
    "Big McIntosh",
    "Sweetie Drops",
    "Winona",
    "DaisyJo",
    "Mrs Cake",
    "Mr Cake",
    "Nurse Redheart",
    "Mule",
    "Lily Valley",
    "Rose",
    "Pinkie Pie, Rainbow Dash",
    "Gilda",
    "Gilda, Rainbow Dash",
    "Merry May",
    "Pony",
    "Snails",
    "Snips",
    "Trixie",
    "Audience",
    "Snails, Snips",
    "Golden Harvest",
    "Ursa",
    "Snails, Snips, Trixie",
    "Unidentified cow",
    "Applejack, Rainbow Dash, Rarity",
    "Snails, Snips, Spike",
    "Angel",
    "Applejack, Pinkie Pie, Rarity",
    "Razer",
    "Applejack, Rarity",
    "Applejack, Rarity, Twilight",
    "All but Twilight",
    "Applejack, Fluttershy, Rainbow Dash",
    "Zecora",
    "Applejack, Pinkie Pie, Rainbow Dash, Rarity",
    "Spike, Twilight Sparkle",
    "Fluttershy, Pinkie Pie, Rarity, Twilight Sparkle",
    "Apple Bloom, Zecora",
    "I all learned an important lesson this week, My friends",
    "Lotus Blossom",
    "All",
    "Parasprite",
    "Parasprites",
    "Rainbow Dash, Rarity, Twilight Sparkle",
    "Parasprite, Spike",
    "Gardening pony",
    "Applejack, Fluttershy, Rainbow Dash, Rarity",
    "Pinkie Pie, Twilight Sparkle",
    "Hedgehogs",
    "Porcupines",
    "Snakes",
    "Applejack, Spike",
    "Caramel",
    "Rainbowshine",
    "Cheerilee",
    "Diamond Tiara",
    "Twist",
    "Silver Spoon",
    "Diamond Tiara, Silver Spoon",
    "Dr Hooves",
    "Ace Point",
    "Roller ponies",
    "Berryshine",
    "Scootaloo",
    "Sweetie Belle",
    "Tornado Bolt",
    "Piña Colada",
    "Coronet",
    "Opalescence",
    "Applejack, Rainbow Dash, Twilight Sparkle",
    "Mane six except Rarity",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash",
    "All except Rarity",
    "Hoity Toity",
    "Twilight",
    "Dumb-Bell",
    "Hoops",
    "Dumb-Bell, Hoops, Score",
    "Applejack, Pinkie Pie, Rarity, Twilight Sparkle",
    "Group",
    "Steam Roller",
    "Foggy Fleece",
    "Madden",
    "Lucy Packard",
    "Meadow Song",
    "Misty Fly",
    "Soarin",
    "Spitfire",
    "Applejack, Pinkie Pie, Twilight Sparkle",
    "Fluttershy, Rarity",
    "Apple Bloom, Scootaloo",
    "Cutie Mark Crusaders",
    "Apple Bloom, Sweetie Belle",
    "Cockatrice",
    "Cutie Mark Crusaders, Fluttershy",
    "Fluttershy, Twilight Sparkle",
    "Frou Frou",
    "Peachy Pie, Sunny Daze",
    "Sapphire Shores",
    "Rover",
    "Fido",
    "Diamond Dogs",
    "Spot",
    "Sir Spike",
    "Mook dogs",
    "Lady Rarity",
    "Fido, Spot",
    "Mook dog",
    "Photo Finish",
    "Background voice",
    "Lyrica Lilac",
    "Royal Ribbon",
    "Gala Appleby",
    "Lemon Hearts",
    "Fluttershy, Pinkie Pie, Rainbow Dash",
    "Fluttershy, Pinkie Pie, Rainbow Dash, Twilight Sparkle",
    "Little Strongheart",
    "Braeburn",
    "Black Stone",
    "Noteworthy",
    "Morton Saltworthy",
    "Ol' Salt",
    "Buffalo",
    "Chief Thunderhooves",
    "Sheriff Silverstar",
    "Goldengrape",
    "Fluttershy, Rainbow Dash, Rarity, Spike, Twilight Sparkle",
    "Settler ponies",
    "Cherry Berry",
    "Mouse family",
    "Guard 1",
    "Guard 2",
    "Philomena",
    "Guard",
    "Hummingway",
    "Mane six except Fluttershy",
    "Count Caesar",
    "Young Applejack",
    "Aunt Orange",
    "Uncle Orange",
    "Tall Order",
    "Dane Tee Dove",
    "Young Fluttershy",
    "Young Dumb-Bell",
    "Young Hoops",
    "Young Rainbow Dash",
    "Rarity's teacher",
    "Young Rarity",
    "Young Twilight Sparkle",
    "Crystal Clear",
    "Arpeggio",
    "Top Marks",
    "Cherry Fizzy",
    "Igneous Rock Pie",
    "Cloudy Quartz",
    "Young Pinkie Pie",
    "Cutie Mark Crusaders, Mane six",
    "Mane six",
    "Owlowiscious",
    "Davenport",
    "Green dragon",
    "Gummy",
    "Pinkie Pie voicing a bucket of turnips",
    "Pinkie Pie voicing a pile of rocks",
    "Pinkie Pie voicing a clump of lint",
    "Pinkie Pie voicing a bag of flour",
    "Pinkie Pie [as Rocky]",
    "Rocky",
    "Sir Lintsalot",
    "Madame le Flour",
    "Mr Turnip",
    "Pinkie Pie [as Mr Turnip]",
    "Pinkie Pie [as Sir Lintsalot]",
    "Pinkie Pie [as Madame le Flour]",
    "Applejack, Fluttershy, Rarity, Twilight Sparkle",
    "Lucky Clover",
    "Prince Blueblood",
    "Mr Greenhooves",
    "Prince Blueblood, Rarity",
    "Joe",
    "Mane six except Spike",
    "Discord",
    "Rarity, Twilight Sparkle",
    "Apples",
    "Red apples",
    "Light-red apples",
    "Green apples",
    "Pond Rainbow Dash",
    "Pond Fluttershy",
    "Pond Pinkie Pie",
    "Pond Rarity",
    "Pond Twilight Sparkle",
    "Discord, Green apples",
    "Balloons",
    "Butterflies",
    "Flashback Discord",
    "Applejack, Fluttershy, Pinkie Pie, Rarity",
    "Applejack, Fluttershy, Pinkie Pie",
    "Crowd",
    "Fillies",
    "Bear",
    "Apple Bloom, Scootaloo, Sweetie Belle",
    "Orange Swirl",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Twilight Sparkle",
    "Pipsqueak",
    "Foals",
    "Background ponies",
    "Pinkie Pie, Pipsqueak",
    "Cloud Kicker",
    "Raven",
    "Several ponies",
    "Sassaflash",
    "Citizens",
    "Noi",
    "Princess Luna (as Nightmare Moon)",
    "Hondo Flanks",
    "Cookie Crumbles",
    "Apple Bloom, Applejack",
    "Sheep",
    "Apple Bloom, Applejack, Rarity",
    "Apple Bloom, Applejack, Sweetie Belle",
    "Rarity, Sweetie Belle",
    "Sea Swirl",
    "Scootaloo, Sweetie Belle",
    "Scootaloo, Sweetie Belle, Twist",
    "Apple Bloom, Applejack, Spike",
    "Daisy, Lily Valley, Rose",
    "Fan club",
    "Aura",
    "Millie",
    "Cream Puff",
    "Pony 1",
    "Pony 2",
    "Lemon Daze",
    "Globe Trotter",
    "Wisp",
    "Crafty Crate",
    "Jack Hammer",
    "Jim Beam",
    "Rivet",
    "Amethyst Star",
    "Pine Breeze",
    "Liza Doolots",
    "Mare Do Well",
    "Pinkie Pie, Spike",
    "Others",
    "Bags Valet",
    "Jet Set",
    "Upper Crust",
    "Hayseed Turnip Truck",
    "Jet Set, Upper Crust",
    "Fancy Pants",
    "Fleur de Lis",
    "Announcer",
    "Silver Frames",
    "Golden Gavel",
    "Swan Song",
    "Fancy Pants, Upper Crust",
    "Junebug",
    "Dr Horse",
    "Dr Fauna",
    "Fluttershy, Rainbow Dash",
    "Spike (flashback)",
    "Rarity (flashback)",
    "Rarity, Spike",
    "Other mane six",
    "Pinkie Pie, Rainbow Dash, Rarity",
    "Pegasi",
    "Unicorns",
    "Applejack, Fluttershy, Twilight Sparkle",
    "Applejack, Fluttershy",
    "Apple Bloom, Applejack, Big McIntosh",
    "Filthy Rich",
    "Apple Strudel",
    "Rest of foals",
    "Foals, Granny Smith",
    "Pound Cake",
    "Pumpkin Cake",
    "Pound Cake, Pumpkin Cake",
    "Derpy",
    "Conductor",
    "Assembled ponies",
    "Parcel Post",
    "Cherry Jubilee",
    "Coach ponies",
    "Rabbit",
    "Fluttershy, Rainbow Dash, Twilight Sparkle",
    "Flam",
    "Flim",
    "Flam, Flim",
    "Apple Bloom, Big McIntosh, Granny Smith",
    "Apple family, Mane six",
    "Comet Tail",
    "Pinkie Pie, Rarity, Twilight Sparkle",
    "Doctor Horse",
    "Nurse Sweetheart",
    "Daring Do",
    "Ahuizotl [with Pinkie Pie's voice]",
    "Nurse Snowheart",
    "Ahuizotl",
    "Spider [with \"Fuzzy Slippers\"'s voice]",
    "Fuzzy Slippers",
    "Screwy",
    "Night Watch",
    "Hay Fever",
    "Persnickety",
    "Big McIntosh, Cheerilee",
    "Karat",
    "Mr Waddle",
    "Matilda",
    "Cranky Doodle Donkey",
    "Cranky Doodle Donkey, Matilda",
    "Sand Trap",
    "Turf",
    "Surf",
    "Gizmo",
    "Roma",
    "Willful Lighting Tech",
    "Willful Stage Manager",
    "Iron Will",
    "Royal Riff",
    "Mr Zippy",
    "Fluttershy, Pinkie Pie, Rarity",
    "Future Twilight Sparkle",
    "Rainbow Dash, Spike",
    "Past Twilight Sparkle",
    "Applejack, Pinkie Pie, Rainbow Dash",
    "Rarity, Spike, Twilight Sparkle",
    "Fume",
    "Clump",
    "Garble",
    "Fizzle",
    "Teenage dragons",
    "Backdraft, Charcoal",
    "Crackle",
    "Charcoal",
    "Rainbow Dash, Rarity, Spike, Twilight Sparkle",
    "Flitter",
    "Film announcer",
    "Thunderlane",
    "Bulk Biceps",
    "Filly Fluttershy",
    "Cloud Chaser",
    "Blossomforth",
    "Cloud Chaser, Flitter",
    "Rumble",
    "Serenity",
    "Slipstream",
    "Students",
    "Truffle",
    "Ruby Pinch",
    "Green Daze",
    "Cotton Cloudy",
    "Shady Daze",
    "Mr Cake, Mrs Cake",
    "Gustave le Grand",
    "Donut Joe",
    "Mulia Mild",
    "Shining Armor",
    "Young Cadance",
    "Young Cadance, Young Twilight",
    "Wild Fire",
    "Princess Cadance",
    "Minuette",
    "Lyra Heartstrings",
    "Royal guard",
    "Queen Chrysalis",
    "Princess Cadance, Twilight Sparkle",
    "Lyra Heartstrings, Minuette, Twinkleshine",
    "Changelings",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Twilight Sparkle",
    "Changelings [as Twilight Sparkle]",
    "Changelings [as Rainbow Dash]",
    "Changeling",
    "Changelings, Queen Chrysalis",
    "Princess Cadance, Shining Armor",
    "Royal guard #1",
    "Royal guard #2",
    "King Sombra",
    "Professor Bill Neigh",
    "Other ponies",
    "Autumn Gem",
    "Fleur De Verre",
    "Elbow Grease",
    "Night Knight",
    "Amethyst Maresbury",
    "Crystal Ponies",
    "Autumn Gem, Fleur De Verre",
    "Crystal Pony",
    "Crystal Beau",
    "Sapphire Joy",
    "Bright Smile",
    "Pinkie Pie 2",
    "Pinkie Pie, Pinkie Pie 2",
    "Pinkie Pie 3",
    "3, 4, Pinkie Pies 2",
    "Pinkie Pie Duplicates",
    "Pinkie Pie Duplicate",
    "Apple Fritter, Applejack, Big McIntosh, Meadow Song",
    "Pinkie Pie Duplicate 2",
    "Pinkie Pie Duplicate 3",
    "Pinkie Pie Duplicate 4",
    "Pinkie Pie Duplicate 5",
    "Pinkie Pie Duplicate 6",
    "Babs Seed",
    "Babs Seed, Diamond Tiara, Silver Spoon",
    "Spectator",
    "Shopkeeper",
    "Rainbow Dash, Snails",
    "Baby Snips",
    "Old Snails",
    "Other ponies, Spike",
    "Baby Snails, Baby Snips",
    "Big McIntosh (as Male Applejack)",
    "Saddle Arabian delegates",
    "Bessie",
    "The Olden Pony",
    "Crocodile",
    "Messenger Pony",
    "All Pegasi",
    "Cloudchaser",
    "Lightning Dust",
    "Meadow Flower",
    "Lightning Dust, Rainbow Dash",
    "Applejack, Fluttershy, Rarity",
    "Fluttershy, Rarity, Twilight",
    "Mane six except Rainbow Dash",
    "Applejack, Fluttershy, Rarity, Twilight",
    "Young Granny Smith",
    "Half Baked Apple",
    "Apple Split",
    "Baby Applejack",
    "Young Apple Rose",
    "Young Apple Rose, Young Granny Smith",
    "Apple Bloom, Granny Smith",
    "Apple Bloom, Babs Seed",
    "Auntie Applesauce",
    "Apple Rose",
    "Apple Rose, Granny Smith",
    "Apple Dumpling",
    "Apple Leaves",
    "Stallions",
    "Apple Rose, Auntie Applesauce, Granny Smith",
    "Applejack, Granny Smith",
    "Fluttershy, Rainbow Dash, Rarity, Twilight Sparkle",
    "Applejack, Pinkie Pie, Rarity, Spike, Twilight Sparkle",
    "Pinkie Pie, Rarity, Spike, Twilight Sparkle",
    "Tank",
    "Opalesence",
    "Laurette",
    "Train Conductor",
    "Cadance, Twilight",
    "Golden Hooves",
    "Ms. Peachbottom",
    "Ms. Harshwhinny",
    "Athletes",
    "Shining Armor, Twilight Sparkle",
    "Royal guard #3",
    "Royal Guard",
    "Cragadile",
    "Cherry Berry, Comet Tail",
    "Plant Crab",
    "All except Twilight",
    "Rest of Mane Six",
    "Ahuizotl [with Fluttershy's voice]",
    "A.K. Yearling",
    "Henchponies",
    "Dr Caballeron",
    "Crusaders",
    "Train conductor",
    "Crusaders, Rainbow Dash",
    "Mane-iac",
    "Henchpony",
    "Rest of Power Ponies",
    "Luggage Cart",
    "Tourist Pony 1",
    "Businesspony",
    "Pronto",
    "Janine Manewitz",
    "Prim Hemline",
    "Suri Polomare",
    "Coco Pommel",
    "Rest of mane six except Rarity",
    "Hinny of the Hills",
    "Applejack, Pinkie Pie",
    "Big McIntosh, Granny Smith",
    "Everypony",
    "Goldie Delicious",
    "Bulk Biceps, Fluttershy",
    "Helia",
    "Mane Moon",
    "Sprinkle Medley",
    "Fleetfoot",
    "Cloudsdale cheerleaders",
    "Rainbowshine, Sprinkle Medley",
    "Fleetfoot, Spitfire",
    "Ponyville team, Wonderbolts",
    "Wonderbolts",
    "Bulk Biceps, Derpy, Fluttershy",
    "Derpy, Rest of mane six",
    "Official",
    "Tatzlwurm",
    "Cheese Sandwich",
    "Today I planned a party, it's just for you!",
    "Vendor Pony",
    "Art Vendor",
    "Peachy Pitt",
    "Colt",
    "I remember this one, Oh",
    "Doctor, tell me what I need",
    "Cheese Sandwich, Pinkie Pie",
    "Trenderhoof",
    "Animals",
    "Torch Song",
    "The Ponytones",
    "Nightjar",
    "Zipporwhill",
    "Nightjar, Zipporwhill",
    "Seedling",
    "Classmate Pony 2",
    "Classmate Pony 3",
    "Seabreeze",
    "Breezies",
    "Twirly",
    "Breezie",
    "Breezette",
    "Applejack, Big McIntosh, Granny Smith",
    "Apple Bloom, Applejack, Granny Smith",
    "Chimera's tiger head",
    "Chimera's goat head",
    "Chimera's snake head",
    "Chimera",
    "Chimera's tiger head, goat head",
    "Duce Switchell",
    "Maud Pie",
    "Sediments",
    "Eclair Crème",
    "Star Gazer",
    "Mint Flower",
    "Little Pony 2",
    "Plum Star",
    "Younger Sweetie Belle",
    "Titania",
    "Backup dancers",
    "Backup dancers, Sapphire Shores",
    "Security guard",
    "Applejack, Big McIntosh",
    "Silver Shill",
    "Jinx",
    "Snappy Scoop",
    "Big McIntosh, Rainbow Dash",
    "Pegasus Stallion #1",
    "Downdraft",
    "Pegasus Stallion #2",
    "High Note",
    "Crowd Pony 1",
    "Crowd Pony 2",
    "Teddie Safari",
    "Cratus",
    "Stellar Eclipse",
    "Match Game",
    "Amethyst Gleam",
    "Crowd Pony 3",
    "Constance",
    "Claude",
    "Mr Robin",
    "Stallion",
    "Crystal Guard",
    "Applejack, Rainbow Dash, Rarity, Twilight Sparkle",
    "Neighls Bohr",
    "Security Guard",
    "Crystal Pony in Crowd",
    "Princess Celestia, Princess Luna",
    "Security Guard 2",
    "All present characters except Spike",
    "Flash Sentry",
    "Duke of Maretonia",
    "Lord Tirek",
    "Rare Find",
    "Princess Cadance, Princess Luna, Twilight Sparkle",
    "Sunny Song",
    "Town pony #1",
    "Town pony #2",
    "Bacon Braids",
    "Town pony #3",
    "Offbeat",
    "\"Princess Erroria\", \"Ruby Pinch\", Cotton Cloudy, Town pony #4",
    "Night Glider",
    "Party Favor",
    "Double Diamond",
    "Starlight Glimmer",
    "Ivy Vine",
    "Burlap",
    "Sugar Belle",
    "Rosemary",
    "Rocky Storm",
    "Aloe",
    "Rainbow Dash, Rarity",
    "Rest of mane six except Twilight",
    "Pest Control Pony",
    "Mysterious Voice",
    "Sunshower",
    "Open Skies",
    "Clear Skies",
    "Clear Skies, Open Skies",
    "Parasol",
    "Fluttershy, Pinkie Pie, Rainbow Dash, Rarity",
    "Townspony 1",
    "Townspony 2",
    "Townspony 3",
    "Townspony 4",
    "Star Spur",
    "Senior Deputy",
    "Trouble Shoes",
    "Young Trouble Shoes",
    "Judges",
    "Female Townspony #1",
    "Male Townspony #1",
    "Female Townspony #2",
    "Judge",
    "Tree Hugger",
    "The Smooze",
    "Apple Bloom, Applejack, Fluttershy, Rainbow Dash, Scootaloo, Tree Hugger",
    "S01E26 Unnamed Earth Mare #1",
    "Grampa Gruff",
    "Arimaspi",
    "Storekeeper",
    "Greta",
    "Young Gilda",
    "Young Gilda, Young Rainbow Dash",
    "Gilda, Pinkie Pie, Rainbow Dash",
    "Jeff Letrotski",
    "Octavia Melody",
    "Walter",
    "Neigh Sayer",
    "Delegate 2",
    "Polo ponies",
    "Horticultural Pegasus",
    "Public Works Pony",
    "\"March Gustysnows, Joe Pescolt\"",
    "Joe Pescolt",
    "March Gustysnows",
    "Annoyed Delegate",
    "Fluffy Clouds",
    "Frazzle Rock",
    "Princess Cadance, Spike",
    "Prince Rutherford",
    "Prince Rutherford, Yaks",
    "Yaks",
    "Mane six except Pinkie",
    "Monster",
    "Mane Six, Princess Celestia, Yaks",
    "Lemon Hearts, Minuette, Twilight Sparkle, Twinkleshine",
    "Lemon Hearts, Minuette, Twinkleshine",
    "Minuette, Twinkleshine",
    "Young Moon Dancer",
    "Moon Dancer",
    "Lemon Hearts, Twinkleshine",
    "All except Moon Dancer",
    "Lemon Hearts, Minuette, Moon Dancer, Twinkleshine",
    "Giant Evil Angel",
    "Sunflowers",
    "Sassy Saddles",
    "Fashion Plate",
    "Fashion Plate, Rarity",
    "Mane six except Rarity, Twilight",
    "Cayenne",
    "Pretzel",
    "Moonlight Raven",
    "Sunshine Smiles",
    "North Point",
    "Citrus Blush",
    "Whoa Nelly",
    "Rarity, Sassy Saddles",
    "Package Deal",
    "Wind Rider",
    "Stormy Flare",
    "Blaze",
    "Castle Guard 1",
    "Spearhead",
    "Cinnamon Chai",
    "Diamond Cutter",
    "Strawberry Ice",
    "Pedestrian Ponies 3 & 4",
    "Pearmain Worcester",
    "Stinky Bottom",
    "Street Pony",
    "Fine Print",
    "Chock-full Carafe",
    "Uptown Clover",
    "On Stage",
    "Raspberry Beret",
    "Late Show",
    "Cloudy Daze",
    "Blueberry Curls",
    "Stardom",
    "Luckette",
    "Pearly Stitch",
    "Viola",
    "Booth Barker",
    "Apple Bloom, Big McIntosh",
    "Rainbow Dash, Scootaloo",
    "Registration Pony",
    "Spoiled Rich",
    "Cheerilee, Foals",
    "Mrs Cake, Pumpkin Cake",
    "Featherweight",
    "Wooden Legs",
    "Mane six except Pinkie Pie",
    "Mane six except Pinkie Pie, Shining Armor",
    "Pound, Pumpkin Cake",
    "Porter Pony",
    "Igneous Rock",
    "Limestone Pie",
    "Marble Pie",
    "Pie family",
    "Apple family, Pie family",
    "Harry",
    "Amethyst Star, Twinkleshine",
    "Mane six except Fluttershy, Pinkie Pie",
    "Flutterbat",
    "Discord, Rainbow Dash",
    "Discord, Fluttershy, Rarity",
    "Mane six except Twilight Sparkle",
    "Mane cast except Twilight Sparkle",
    "Discord, mane six except Twilight Sparkle",
    "Discord, Mane six",
    "Ma Hooffield",
    "Buzzard Hooffield",
    "Mice",
    "Steel Bolts",
    "Rosy Riveter",
    "Big Daddy McColt",
    "McColts",
    "McColt Guards",
    "Hacksaw McColt",
    "Hooffields",
    "Big Daddy McColt, Ma Hooffield",
    "Lyra Heartstrings, Sweetie Drops",
    "Fluttershy, Noteworthy, Rainbow Dash, Rarity, Royal Riff, Spike, Sprinkle Medley, Twilight Sparkle",
    "Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Royal Riff, Spike, Sprinkle Medley, Twilight Sparkle",
    "Svengallop",
    "Coloratura",
    "Audience Pony",
    "Hoops, Young Dumb-Bell",
    "Fluttershy, Hoops, Young Dumb-Bell",
    "Starlight Glimmer, Twilight Sparkle",
    "Sunburst",
    "Scarlet Heart",
    "Amber Laurel",
    "Golden Väs",
    "Flurry Heart",
    "Cloudy Spinel",
    "Coral Shores",
    "Tough Nut",
    "Scouts Honor",
    "Mustafa Combe",
    "Spike, Starlight Glimmer",
    "Night Light",
    "Twilight Velvet",
    "Deputy Copper",
    "Street Rat",
    "Hoofer Steps",
    "Tender Taps",
    "Dragon Lord Torch",
    "Dragons",
    "Princess Ember",
    "Maar",
    "Barry",
    "Cherry Berry, Goldengrape",
    "Caramel, Shoeshine, Sunshower Raindrops",
    "Starlight Glimmer, Trixie",
    "Rainbow Dash, Spitfire",
    "Young Hoops, Young Pegasi",
    "Fleetfoot, High Winds, Misty Fly, Soarin, Surprise",
    "Rainbow Dash, Surprise",
    "Surprise",
    "Cutie Mark Crusaders, Rest of mane six",
    "High Winds",
    "Professor Flintheart",
    "Young Starlight Glimmer",
    "Buried Lede",
    "Mr Stripes",
    "Plaid Stripes",
    "Rarity Devil",
    "Rarity Angel",
    "Dancers",
    "Blue Bobbin",
    "Waxton",
    "Lavender Essence",
    "Buddy",
    "Birch Bucket",
    "Mrs Shy",
    "Mr Shy",
    "Zephyr Breeze",
    "Saffron Masala",
    "Coriander Cumin",
    "Chargrill Breadwinner",
    "Orange Slice",
    "Pinkie Pie, Saffron Masala",
    "Zesty Gourmand",
    "Coriander Cumin, Pinkie Pie, Rarity",
    "Coriander Cumin, Saffron Masala",
    "Coriander Cumin, Pinkie Pie",
    "Sweet Biscuit",
    "Burly Unicorn",
    "Matronly Pony",
    "Salespony",
    "Quibble Pants, Rainbow Dash",
    "Quibble Pants",
    "A. K. Yearling",
    "Pickpocket",
    "Cipactli",
    "Dr Caballeron, henchponies",
    "Upper class ponies",
    "Mrs Cake, Pinkie Pie",
    "Lyra Heartstrings, Twinkleshine",
    "Zombie ponies",
    "Honeysparkle",
    "Royal guard 1",
    "Royal guard 2",
    "Thorax",
    "Baby Thorax",
    "Spike, Thorax",
    "Royal guards, Shining Armor",
    "Princess Cadance, Sunburst",
    "Opposite Fluttershy",
    "Mini-Discord",
    "Big McIntosh, Spike",
    "Squizard",
    "Big McIntosh, Discord, Spike",
    "Discord, Spike",
    "Crimson Heart",
    "Aloha",
    "Fluttershy, Pinkie Pie",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Snails",
    "Mrs Paleo",
    "Mr Paleo",
    "Petunia Paleo",
    "Mr Paleo, Mrs Paleo",
    "Gabby",
    "Elderly griffon",
    "Barker",
    "Gladmane",
    "Trapeze Star",
    "Director",
    "Roar Horn",
    "Sprigfield",
    "Bernard Rabbit",
    "Back Stage",
    "\"Sprigfield, Roar Horn\"",
    "Young Big McIntosh",
    "Young Applejack, Young Big McIntosh",
    "Spoiled Milk",
    "Granny Smith, Young Applejack",
    "Granny Smith, Young Big McIntosh",
    "Hippocratic Oath",
    "Doctor Spring Bud",
    "Open Heart",
    "Angel Wings",
    "Sky Stinger",
    "Rest of recruits",
    "Recruits",
    "Vapor Trail",
    "Twirly Whirly",
    "Steer Straight",
    "Young Vapor Trail",
    "Young Sky Stinger",
    "Double Diamond, Party Favor",
    "Village ponies",
    "Princess Luna, Starlight Glimmer",
    "Changeling Twilight",
    "Pigasus",
    "Thorax, Trixie",
    "Fluttershys",
    "Fluttershy #1",
    "Fluttershy #2",
    "Fluttershy #3",
    "Fluttershy #4",
    "Starlight Glimmer, Thorax",
    "Changeling Girl",
    "Changeling 1",
    "Goofy Changeling",
    "Cornicle",
    "Princess Ember, Starlight Glimmer",
    "Sunburst, Twilight Sparkle",
    "Ginger Locks",
    "Clarity Cut",
    "Cake Twins, Flurry Heart",
    "Cake Twins",
    "Foals, Nurse Redheart",
    "Flurry Heart, Twilight Sparkle",
    "Peach Fuzz",
    "Rusty Tenure",
    "Clementine",
    "Dr Fauna, Fluttershy",
    "All except Fluttershy",
    "Rupert",
    "Dandy Grandeur",
    "Wrangler",
    "Hard Hat",
    "Dandy Grandeur, Hard Hat, Wrangler",
    "Jack Hammer, Steam Roller",
    "Starry Eyes",
    "Chipcutter",
    "Ripley",
    "Apple Bloom, Scootaloo, Zipporwhill",
    "Bow Hothoof",
    "Windy Whistles",
    "Bow Hothoof, Windy Whistles",
    "Bow Hothoof, Rainbow Dash, Windy Whistles",
    "Feather Bangs",
    "Swooning Ponies",
    "Swoon Song",
    "Fond Feather",
    "Big McIntosh, Sugar Belle",
    "Inky Rose, Lily Lace, Starstreak",
    "Lily Lace",
    "Starstreak",
    "Inky Rose",
    "Hoity Toity, Photo Finish",
    "Hoity Toity, Lily Lace, Rarity",
    "All except Applejack",
    "Strawberry Sunrise",
    "\"Rivet\", Hard Hat, Jack Hammer, Steam Roller",
    "Delegate Ponies",
    "Mayor Cream Cheese",
    "Mayor Baltimare",
    "Mayor Baltimare, Mayor Cream Cheese",
    "Pancakes",
    "Daybreaker",
    "Princess Celestia, Starlight Glimmer",
    "Dream Ponies",
    "Dream Pony",
    "Pinkie Pie, Prince Rutherford, yaks",
    "Pinkie Pie, yaks",
    "Yak Kid 1",
    "Yak Kid 2",
    "Prince Rutherford, yak",
    "Prince Rutherford, yaks",
    "Yak",
    "Discord, Fluttershy",
    "Discord's finger",
    "Discord 2",
    "Jasmine Leaf",
    "Raspberry Vinaigrette",
    "Piñata",
    "Discord 3",
    "Other Discords",
    "All Discords",
    "Grand Pear",
    "Young Grand Pear",
    "Young Bright Macintosh",
    "Young Pear Butter",
    "Burnt Oak",
    "Bright Mac",
    "Pear Butter",
    "Bright Mac, Pear Butter",
    "Chiffon Swirl",
    "Young Mayor Mare",
    "Grand Pear, Granny Smith",
    "Toola Roola",
    "Coconut Cream",
    "Coconut Cream, Toola Roola",
    "Out of Town Pony",
    "Out of Town Pony 2",
    "Lavender Bloom",
    "Princess Erroria",
    "Pegasus Fillies",
    "Glasses Stallion",
    "Lemon Chiffon",
    "Sweet Apple Admirer",
    "Reporter Pony",
    "Ember",
    "Crusoe Palm",
    "Rainbow Stars",
    "\"Rainbow Stars\", Crusoe Palm",
    "Ember, Thorax",
    "Spike, Starlight Glimmer, Twilight Sparkle",
    "Ember, Spike, Thorax",
    "Mighty Helm ponies",
    "Rockhoof",
    "Rainbow Dash, Scootaloo, Sweetie Belle",
    "All except Rainbow Dash",
    "All except Sweetie Belle",
    "Mistmane",
    "Villager",
    "Foal",
    "Sable Spirit",
    "Flash Magnus",
    "Commander Ironhead",
    "Pharynx",
    "Sclerite",
    "Frenulum",
    "Green Changeling",
    "Tymbal",
    "Changeling 2",
    "Changeling 3",
    "All changelings",
    "Young Changeling",
    "Young Pharynx",
    "Young Thorax",
    "Passing Changeling",
    "Newspaper Pony",
    "Cortland",
    "Mrs Trotsworth",
    "Random Villager",
    "Nile Faras",
    "Mr Breezy",
    "Chelsea Porcelain",
    "Creature",
    "Customer Pony",
    "Silver Medal",
    "Rest of mane six, Starlight Glimmer",
    "Daisy, Lily Valley",
    "Cattail",
    "Fluttershy, Mage Meadowbrook",
    "Chipmunk",
    "Meadowbrook's Mother",
    "Mage Meadowbrook",
    "Royal Pin",
    "Kettle Corn",
    "Skeedaddle",
    "Sparkle family",
    "Rest of the Sparkle family",
    "Night Light, Twilight Velvet",
    "Raspberry Sorbet",
    "Cruise Ponies",
    "Sunny Side",
    "Star Tracker",
    "Sun Cloche",
    "Cruise ponies",
    "Fan",
    "Flurry Heart, Princess Cadance",
    "Everypony else",
    "Cruise pony",
    "Janitor Pony",
    "Fleetfoot, Soarin, Spitfire",
    "EMT Pony",
    "All Aboard",
    "Young Sunburst",
    "All except Maud Pie",
    "Star Swirl the Bearded",
    "Pony of Shadows",
    "Professor Fossil",
    "Lotus Petal",
    "Billy",
    "Dragon",
    "Fahal Alkhayl",
    "Somnambula",
    "Sirens",
    "Aria Blaze",
    "Stygian",
    "Neighsay",
    "Sandbar",
    "Gallus",
    "Yona",
    "Smolder",
    "Silverstream",
    "Seaspray",
    "Ocellus",
    "Gallus, Yona",
    "Ocellus, Silverstream, Yona",
    "Silverstream, Smolder",
    "Ember, Grampa Gruff, Prince Rutherford, Seaspray, Thorax",
    "Sandbar, Smolder",
    "Rest of students",
    "Mudbriar",
    "Fluttershy's apparition",
    "Rarity's apparition",
    "Applejack's apparition",
    "Rainbow Dash's apparition",
    "Twilight Sparkle's apparition",
    "Mane five's apparitions",
    "Background pony 1",
    "Background pony 2",
    "Background pony 3",
    "Background pony 4",
    "Pursey Pink",
    "Pursey Pink, Rarity",
    "Bracer Britches",
    "Silver Berry",
    "Old Money",
    "Valley Trend",
    "Snow Hope",
    "Joan Pommelway",
    "Mare E. Lynn",
    "Applejack, Pinkie Pie, Rainbow Dash, Spike, Twilight Sparkle",
    "Applejack, Pinkie Pie, Rainbow Dash, Twilight Sparkle",
    "Grannies",
    "Applejack vision",
    "Cranberry Muffin",
    "Tight End",
    "Carnival Barker",
    "Jack Pot",
    "Big Bucks",
    "Terramar",
    "Sky Beak",
    "Cutie Mark Crusaders, Twilight Sparkle",
    "Ocean Flow",
    "Applejack, Fluttershy, Rainbow Dash, Rarity, Starlight Glimmer",
    "Young Six",
    "All except Pinkie Pie",
    "All except Twilight Sparkle",
    "Mail Pony",
    "Starlight Glimmer, Sunburst, Twilight Sparkle",
    "Automated voice",
    "Ever Essence",
    "Raspberry Latte",
    "Minty Mocha",
    "Firelight",
    "Stellar Flare",
    "Firelight, Stellar Flare",
    "Starlight Glimmer, Sunburst",
    "Cracked Wheat",
    "\"Minty Mocha, \"Raspberry Latte\", Ever Essence\"",
    "Rest of Young Six",
    "Gallus, Smolder",
    "Peewee",
    "Tourist Pony",
    "Citrine Spark",
    "Berry Bliss",
    "Cozy Glow",
    "Apple Bloom, Cozy Glow",
    "Cozy Glow, Cutie Mark Crusaders",
    "Photographer",
    "Mean Pinkie Pie",
    "Mean Fluttershy",
    "Mean Rarity",
    "Mean Applejack",
    "Mean Rainbow Dash",
    "Mean Twilight Sparkle",
    "Bird 1",
    "Bird 2",
    "Applejack, Rainbow Dash, Rarity, Starlight Glimmer",
    "Mean Applejack, Mean Pinkie Pie, Mean Rarity",
    "Rarity, Starlight Glimmer",
    "All except Twilight Sparkle, Fluttershy",
    "Mean Ponies",
    "Mean Fluttershy, Mean Rarity",
    "Applejack, Starlight Glimmer",
    "Mane Six except Applejack",
    "Discord 1",
    "All three Discords",
    "Voice on bananaphone",
    "Ocellus, Smolder",
    "King Grover Painting",
    "Gallus, Silverstream",
    "Changeling Painting",
    "Pony Painting",
    "Discord's Ghost",
    "Rainbow Dash, Spike, Twilight Sparkle",
    "All except Yona",
    "All except Sandbar",
    "All except Gallus",
    "Polo Play",
    "Chancellor Neighsay",
    "Destitute Pony",
    "Student 4",
    "Cherry Fizzy, Lyra Heartstrings, Rose, Savoir Fare, Sweetie Drops",
    "Bufogren",
    "Mane Six except Pinkie Pie",
    "Rest of the Mane Six",
    "Yak waiter",
    "Yigrid",
    "Fluttershy, Rainbow Dash, under",
    "Hoo'Far",
    "Tall Pony",
    "Short Pony",
    "Round Pony",
    "Rainy Day",
    "Snow Violet",
    "\"Snow Violet, Rainy Day\"",
    "Announcer, Crowd",
    "Fanpony",
    "Rolling Thunder, Short Fuse",
    "Rolling Thunder",
    "Short Fuse",
    "Gallus, Silverstream, Yona",
    "Hippogriff Sailor",
    "Ocellus, Sandbar",
    "Illusion Twilight Sparkle",
    "Stepford Pony 1",
    "Stepford Pony 2",
    "Illusion Rarity",
    "Illusion Rainbow Dash",
    "Spindle",
    "Tree of Harmony",
    "Silverstream, Yona",
    "Loose Tracks",
    "Autumn Blaze",
    "Spoiler alert",
    "No more talking,",
    "Rain Shine",
    "Sludge",
    "Mane Six, Spike",
    "Sludge, Spike",
    "Special Delivery",
    "Patty Peppermint",
    "Cerberus",
    "Cutie Mark Crusaders, Sandbar",
    "Young Six except Sandbar",
    "Chancellor Neighsay, Twilight Sparkle",
    "All except Cutie Mark Crusaders",
    "Grogar",
    "Lord Tirek, Queen Chrysalis",
    "Rest of Mane Six, Starlight Glimmer",
    "Rest of Mane Six, Spike",
    "Star Swirl",
    "Mane Six except Twilight Sparkle",
    "Mane Six, Princess Celestia, Princess Luna",
    "Cozy Glow, Lord Tirek, Queen Chrysalis",
    "Tourists",
    "Server Pony",
    "Saturn",
    "BeauDe Mane",
    "Dusty Pages",
    "Librarian Pony",
    "First Folio",
    "Meathead Pony",
    "Old Stallion",
    "Dusty Pages, Spike",
    "Male Pony",
    "Clear Sky",
    "Wind Sprint",
    "Game Announcer",
    "Referee",
    "Clear Sky, Quibble Pants, Wind Sprint",
    "Gallus, Ocellus, Smolder",
    "Gallus, Ocellus, Silverstream, Smolder",
    "Sandbar, Yona",
    "Rusty Bucket",
    "Cozy Glow, Lord Tirek",
    "Cozy Glow, Queen Chrysalis",
    "Fluttershy, Smolder, Spike",
    "Dragons, Garble",
    "\"Billy\", Clump, Fume",
    "Goldie Delicious, Granny Smith",
    "Student Pony",
    "Sunburst, Trixie",
    "Sunburst, Terramar, Trixie",
    "Edith",
    "Aunt Holiday",
    "Auntie Lofty",
    "Cheerilee, foals",
    "Snap Shutter",
    "Mane Allgood",
    "Mr Tortoise-Snap",
    "Guard Pony 1",
    "Guard Pony 2",
    "Sans Smirk",
    "Factory Pony",
    "Lighthoof, Shimmy Shake",
    "Lighthoof",
    "Shimmy Shake",
    "Cheer Squad",
    "Pizzelle",
    "November Rain",
    "Ocellus, Yona",
    "School of Friendship Team",
    "Apple Honey",
    "Apple Cobbler",
    "Feather Flatterfly",
    "Fire Flare",
    "Unicorn 1",
    "Antoine",
    "Muriel",
    "Sandra",
    "Scout",
    "Gabby, Spike",
    "Pinkie Pie, Rarity, Spike",
    "All except Starlight Glimmer",
    "Dad Changeling",
    "Yona's Dad, Yona's Mom",
    "Groom Q. Q. Martingale",
    "Rogue",
    "Dr Caballeron, Fluttershy, henchponies",
    "Withers",
    "Biff",
    "Daring Do, Dr Caballeron",
    "Spur",
    "Biscuit",
    "\"Savage Honeydew, Spring Green\"",
    "Bloofy",
    "Passerby Pony",
    "Talking Apple",
    "Talking Apple 2",
    "Talking Apple 3",
    "Cutie Mark Crusaders, Granny Smith",
    "Giant Apple",
    "Large Apple",
    "Unicorn Baker",
    "Fruit Seller",
    "Pillars",
    "Queen Chrysalis, Starlight Glimmer",
    "Royal Guards",
    "Princess Celestia, Princess Luna, Twilight Sparkle",
    "Winter Lotus",
    "S08E14 Unnamed Earth Mare #4",
    "Earth Pony 2",
    "Cotton Sky",
    "Hyper Sonic",
    "Rasberry[sic] Dazzle",
    "Future Spike",
    "Future Gallus",
    "Luster Dawn",
    "Baker Pony",
    "Future Pinkie Pie",
    "Future Rarity",
    "Future Rainbow Dash",
    "Future Applejack",
    "Future Fluttershy",
    "Future Mane Six, Spike",
    "Mane Six, Spike, Starlight Glimmer",
    "Mane cast except Pinkie",
    "Mane six except Rainbow",
    "Main ponies",
    "Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Spike",
    "Sunset Shimmer",
    "Principal Celestia",
    "Big Mac",
    "Voice on P.A. system",
    "Nolan North",
    "Vice Principal Luna",
    "Scott Green",
    "Cloudy Kicks",
    "Girl #2",
    "Girl #3",
    "Brawly Beats",
    "Applejack, Fluttershy, Pinkie Pie, Princess Cadance, Rainbow Dash, Rarity",
    "Flash Sentry, Twilight Sparkle",
    "My Little Pony Equestria Girls",
    "Carl Pettington",
    "Emilia Furhart",
    "Curtis Pawpower",
    "Fido, Rover, Spot",
    "Female Patron",
    "The Dazzlings",
    "Adagio Dazzle",
    "Sonata Dusk",
    "Aria Blaze, Sonata Dusk",
    "The Rainbooms",
    "Blueberry Cake",
    "The Dazzlings, students",
    "Cherry Crash",
    "Captain Planet",
    "Delivery Pony",
    "Applejack, Fluttershy, Pinkie Pie, Rainbow Dash, Rarity, Sunset Shimmer",
    "Sunset Shimmer, Twilight Sparkle",
    "Maud",
    "Male Student",
    "Principal Celestia, Vice Principal Luna",
    "Ringo",
    "Male student",
    "Rainbooms, Sunset Shimmer",
    "Mane six except Twilight, Sunset Shimmer",
    "Flash Sentry, Mane six, Sunset Shimmer",
    "Sci-Twi",
    "Puppy Spike",
    "Said Thunderbolt",
    "Sandalwood",
    "Japanese Voice-Over Guy",
    "Micro Chips",
    "Miss Cheerilee",
    "All except Sunset Shimmer",
    "All except Rarity, Luna, Sunset Shimmer",
    "Dean Cadance",
    "Principal Cinch",
    "Sour Sweet",
    "Indigo Zap",
    "Bus Driver",
    "Sugarcoat",
    "Lemon Zest",
    "Sunny Flare",
    "Sweet Leaves",
    "Mystery Mint",
    "Scribble Dee",
    "Sophisticata",
    "Velvet Sky",
    "Starlight",
    "All except Sci-Twi",
    "Sci-Twi, Sunset Shimmer",
    "Crystal Prep Students",
    "The Main Six",
    "Cat",
    "Puppy Spike, Sci-Twi",
    "Lemon Zest, Sunny Flare",
    "Everfree Forest creature",
    "Midnight Sparkle",
    "Daydream Shimmer",
    "The Equestria Girls",
    "Spike, Sunset Shimmer",
    "Gloriosa Daisy",
    "Timber Spruce",
    "Rainbow Dash, Sunset Shimmer",
    "Timber Spruce, Twilight Sparkle",
    "Everybody except Sunset, Twilight",
    "Flash Sentry, Sunset Shimmer",
    "Sunset Shimmer's voice",
    "Rarity's voice",
    "Rainbow Dash's voice",
    "Pinkie Pie's voice",
    "Applejack's voice",
    "Fluttershy's voice",
    "Equestria Girls",
    "TV announcer",
    "Fluttershy, Sunset Shimmer",
    "Shadowbolts",
    "The Equestria Girls except Rarity",
    "Rarity, Sour Sweet",
    "Stalwart Stallion",
    "Canter Zoom",
    "P.A.",
    "Chestnut Magnifico",
    "Juniper Montage",
    "Canter Zoom, The Equestria Girls",
    "Nervous P.A.",
    "The Equestria Girls except Rainbow Dash",
    "Boss",
    "Reflection Juniper Montage",
    "Fans",
    "Patron",
    "Child",
    "Watermelody",
    "Juniper Montage, Starlight Glimmer",
    "Juniper Montage, Pinkie Pie",
    "Fluttershy, Starlight Glimmer, Sunset Shimmer",
    "Princess Twilight Sparkle",
    "Male students",
    "Fluttershy, Students",
    "Fluttershy, Pinkie Pie, students",
    "Pinkie Pie, Rainbow Dash, Twilight Sparkle",
    "Student",
    "Voice on phone",
    "Pinkie Pie, Sunset Shimmer",
    "Slingshot",
    "Dog",
    "Heath Burns",
    "Young Girl",
    "Cashier",
    "Lily Pad",
    "Rest of the Equestria Girls",
    "Museum Employee",
    "Cranky Doodle",
    "Hubert",
    "Jewelry Store Owner",
    "Biker",
    "Thief",
    "Female Director",
    "Pinkie Pie, Sunset Shimmer, Twilight Sparkle",
    "Carrot Bun",
    "Baby turtle",
    "Baby turtles",
    "Little boy",
    "Mother",
    "Woman 2",
    "Applejack, Timber Spruce",
    "Pup-Pup",
    "Mr Puppy",
    "Peacock Plume",
    "Crystal Prep students",
    "Sunny Sugarsocks",
    "Pinkie Pie, Sunny Sugarsocks",
    "Best in Show",
    "Banana",
    "Bulk Biceps' dog",
    "Rosette Nebula",
    "Doo Wop",
    "Garden Grove",
    "Old Lady",
    "Doo Wop, Sunny Sugarsocks",
    "Taxi Driver",
    "Rest of Equestria Girls",
    "Lighting Girl",
    "Band Member",
    "Person in Line",
    "\"R, F\" is for freedom",
    "\"E, I\" is inspired",
    "\"D, N\", never-ending",
    "Applejack, Rarity, Twilight Sparkle",
    "\"Mystery Mint, Cherry Crash\"",
    "Applejacks",
    "Rarity Investigates",
    "Curly Winds",
    "Mr Cranky Doodle",
    "Applejack, Cutie Mark Crusaders, Rainbow Dash",
    "Vignette Valencia",
    "Princess Thunder Guts",
    "Supernova Zap",
    "Princess Thunder Guts, Spike",
    "Fluttershy, Rarity, Twilight Sparkle",
    "Dirk Thistleweed",
    "Dirk Thistleweed, Snails, Snips",
    "Principal Celestia, Twilight Sparkle",
    "Fanboy",
    "Melon Mint",
    "CHS Soccer Players",
    "CPA Soccer Coach",
    "Teddy",
    "Employee",
    "Applejack, Sunset Shimmer",
    "Sunset Shimmer, Wallflower Blush",
    "Wallflower Blush",
    "Princess Twilight Sparkle, Sunset Shimmer",
    "Princess Celestia, Sunset Shimmer",
    "Princess Celestia, Princess Twilight Sparkle, Sunset Shimmer",
    "Designer",
    "Lyra Heartstrings, Sweetie Drops, Trixie",
    "Rarity, Vignette Valencia",
    "Equestria Girls except Applejack",
    "Little Girl",
    "Little Boy",
    "Rest of the Equestria Girls except Sunset",
    "Puffed Pastry",
    "Ragamuffin",
    "Rainbow Dash's voicemail",
    "Parrot",
    "Both Twilights, Rainbow Dash, Sunset Shimmer",
    "Pinkie Pie (pony)",
    "Pinkie Pie, Puffed Pastry",
    "Festival Artist",
    "Security Guard, Sunset Shimmer",
    "Festival Intern",
    "Kiwi Lollipop",
    "Kiwi Lollipop, Sunset Shimmer",
    "Kiwi Lollipop, Pinkie Pie, Sunset Shimmer, Supernova Zap",
    "Equestria Girls except Pinkie Pie",
    "Chad",
    "Janitor",
    "Wiz Kid",
    "Alizarin Bubblegum",
    "Celery Stalk",
    "Rest of Equestria Girls except Pinkie Pie",
    "Smallfry",
    "Dishwater Slog",
    "Mane Six except Rainbow Dash",
    "Dishwater Slog, Rainbow Dash",
    "Derek",
    "Matt 1",
    "Matt 2",
    "Bubbles",
    "Bubbles, Fluttershy",
    "Bookstore Pony",
    "Fluttershy, Spike, Twilight Sparkle",
    "Buttershy",
    "Inner Pinkie Pie",
    "Inner Fluttershy",
    "Inner Rarity",
    "Fluttershy, Foals",
    "TV Producer Pony",
    "Pinkie Pie, Rainbow Dash, Rarity, Twilight Sparkle",
    "Pinkie Pie Hologram",
    "Angel Bunny",
    "Applejack, Fluttershy, Rainbow Dash, Twilight Sparkle",
    "Mane Six except Rarity",
    "Fluttershy, Pinkie Pie, Twilight Sparkle",
    "Cupcake Monster",
    "Finn Tastic",
    "Producer Pony",
    "Potion Nova",
    "Stranger Pony",
    "Mane Six, Potion Nova",
    "Potion Nova, Twilight Sparkle",
    "Cookie Twilight Sparkle",
    "Cookie Rarity",
    "Cookie Applejack",
    "Cookie Rainbow Dash",
    "Cookie Ponies",
    "Pinkie Pie, Producer Pony",
    "Fan Pony",
    "Ponies, Spike",
    "Mane Six except Applejack, Spike",
    "Pinkie Pie, Twilght Sparkle",
    "Twilght Sparkle",
    "Tablet",
    "Voice",
    "Disembodied Voice",
    "Danger Dash",
    "Applejack, Danger Dash, Twilight Sparkle",
    "Danger Dash, Spike",
    "Apple",
    "Octavio Pie",
    "Octavio Pie, Pinkie Pie",
    "Boss Pony",
    "Herd Happily",
    "Karen",
    "Finn Tastic, Ponies",
    "Zesty",
    "Reuse Pony",
    "Crowd, Mane Six",
    "Balloonga",
    "Rarity's Reflection",
    "Hawthorne",
    "Serene Voice",
    "Cowgirl Pony",
    "Saddle Bags",
    "Cowboy Pony",
    "Natalie, Pulverizer",
    "Pulverizer",
    "Natalie",
    "QT-PI3",
    "Alternate Six, Mane Six",
    "Lightning Chill",
    "Echo",
    "Mane Six, Wild Siders",
    "Sugar Snap",
    "Wild Siders",
    "Echo, Sugar Snap",
    "Bighoof",
    "Lightning Chill, Pinkie Pie",
    "Lightning Chill, Pinkie Pie, Sugar Snap",
    "Rest of Mane Six, Wild Siders",
    "Rarity, Sugar Snap",
    "Applejack, Echo, Pinkie Pie, Twilight Sparkle",
    "Applejack, Echo, Pinkie Pie, Rainbow Dash",
    "Pony Running the Booth",
    "Face Painter",
    "Curtain Call",
    "Assistant",
    "Shoulder Angel Rarity 1",
    "Shoulder Angel Rarity 2",
    "Makeup Ponies",
    "Chamomilia",
    "Big McIntosh, Rest of Mane Six",
    "Reuse Pony (M)",
    "Magic",
    "3-Headed Bunny (Right Head)",
    "3-Headed Bunny (Middle Head)",
    "3-Headed Bunny (Left Head)",
    "3-Headed Bunny (All)",
    "Muffins",
    "Echo, Rest of Mane Six, Spike, Sugar Snap",
    "S04E26 Unnamed Earth Mare #1",
    "Female Pony 2",
    "Code Red",
    "Songbird Serenade",
    "Female pony",
    "Vinny",
    "Whinnyfield",
    "Grubber",
    "Tempest Shadow",
    "The Storm King",
    "Rainbow Dash, Rarity, Spike",
    "Pig Creature 1",
    "Pig Creature 2",
    "Pig Creatures",
    "Vendor 1",
    "Vendor 2",
    "Pushkin",
    "Capper",
    "Mori",
    "Louise",
    "Vera",
    "Deer Creature",
    "Creature 1",
    "Scaly Klugetowner",
    "Toothy Klugetowner",
    "Verko",
    "Boyle",
    "Squabble",
    "Mullet",
    "Lix Spittle",
    "Captain Celaeno",
    "Mane Six except Twilight",
    "Princess Skystar",
    "Queen Novo",
    "Jamal",
    "Female seapony",
    "Rest of the Mane Six, Spike",
    "Boyle, other pirates",
    "Storm Creature",
    "Sheldon, Shelly",
    "The Storm King, Twilight Sparkle",
    "Pinkie Pie, Princess Skystar",
    "Hey (hey!), where you gonna go?",
    "Alice",
    "Yojan",
    "Pony Vendor 1",
    "Pony Vendor 2",
    "Top Notch",
    "Holly the Hearth's Warmer Doll",
    "Butternut",
    "Oak Nut",
    "Pistachio",
    "Aurora",
    "Alice, Pinkie Pie",
    "Bori",
    "Alice, Aurora, Bori",
    "Alice, Bori",
    "Hughbert Jellius",
    "Burning passion",
    "Minty Bubblegum",
    "All except Discord",
    "Rest of cast",
    "Loudspeaker",
    "Baby Twilight Sparkle",
    "Crowd Pony",
    "My Little Pony",
    "Petunia Petals",
    "Man Pony",
    "Barley Barrel, Pickle Barrel",
    "Barley Barrel",
    "Pickle Barrel",
    "Mrs Hoofington",
    "Mr Hoofington",
    "Mr, Mrs Hoofington",
    "Moody Root",
    "Mayor Sunny Skies",
    "Torque Wrench",
    "Trout Pony",
    "Barley, Pickle Barrel",
    "Kerfuffle",
    "Pony #1",
    "Pony #2",
    "Petunia Petals, Twilight Sparkle",
    "Applejack, Torque Wrench",
    "Applejack, Petunia Petals, Torque Wrench, Twilight Sparkle",
    "Customer #1",
    "Girl Pony"
]
const titles = {
    "101": "Friendship is Magic, part 1",
    "102": "Friendship is Magic, part 2",
    "103": "The Ticket Master",
    "104": "Applebuck Season",
    "105": "Griffon the Brush Off",
    "106": "Boast Busters",
    "107": "Dragonshy",
    "108": "Look Before You Sleep",
    "109": "Bridle Gossip",
    "110": "Swarm of the Century",
    "111": "Winter Wrap Up",
    "112": "Call of the Cutie",
    "113": "Fall Weather Friends",
    "114": "Suited For Success",
    "115": "Feeling Pinkie Keen",
    "116": "Sonic Rainboom",
    "117": "Stare Master",
    "118": "The Show Stoppers",
    "119": "A Dog and Pony Show",
    "120": "Green Isn't Your Color",
    "121": "Over a Barrel",
    "122": "A Bird in the Hoof",
    "123": "The Cutie Mark Chronicles",
    "124": "Owl's Well That Ends Well",
    "125": "Party of One",
    "126": "The Best Night Ever",
    "201": "The Return of Harmony Part 1",
    "202": "The Return of Harmony Part 2",
    "203": "Lesson Zero",
    "204": "Luna Eclipsed",
    "205": "Sisterhooves Social",
    "206": "The Cutie Pox",
    "207": "May the Best Pet Win!",
    "208": "The Mysterious Mare Do Well",
    "209": "Sweet and Elite",
    "210": "Secret of My Excess",
    "211": "Hearth's Warming Eve",
    "212": "Family Appreciation Day",
    "213": "Baby Cakes",
    "214": "The Last Roundup",
    "215": "The Super Speedy Cider Squeezy 6000",
    "216": "Read It and Weep",
    "217": "Hearts and Hooves Day",
    "218": "A Friend in Deed",
    "219": "Putting Your Hoof Down",
    "220": "It's About Time",
    "221": "Dragon Quest",
    "222": "Hurricane Fluttershy",
    "223": "Ponyville Confidential",
    "224": "MMMystery on the Friendship Express",
    "225": "A Canterlot Wedding - Part 1",
    "226": "A Canterlot Wedding - Part 2",
    "301": "The Crystal Empire - Part 1",
    "302": "The Crystal Empire - Part 2",
    "303": "Too Many Pinkie Pies",
    "304": "One Bad Apple",
    "305": "Magic Duel",
    "306": "Sleepless in Ponyville",
    "307": "Wonderbolts Academy",
    "308": "Apple Family Reunion",
    "309": "Spike at Your Service",
    "310": "Keep Calm and Flutter On",
    "311": "Just for Sidekicks",
    "312": "Games Ponies Play",
    "313": "Magical Mystery Cure",
    "401": "Princess Twilight Sparkle - Part 1",
    "402": "Princess Twilight Sparkle - Part 2",
    "403": "Castle Mane-ia",
    "404": "Daring Don't",
    "405": "Flight to the Finish",
    "406": "Power Ponies",
    "407": "Bats!",
    "408": "Rarity Takes Manehattan",
    "409": "Pinkie Apple Pie",
    "410": "Rainbow Falls",
    "411": "Three's A Crowd",
    "412": "Pinkie Pride",
    "413": "Simple Ways",
    "414": "Filli Vanilli",
    "415": "Twilight Time",
    "416": "It Ain't Easy Being Breezies",
    "417": "Somepony to Watch Over Me",
    "418": "Maud Pie",
    "419": "For Whom the Sweetie Belle Toils",
    "420": "Leap of Faith",
    "421": "Testing Testing 1, 2, 3",
    "422": "Trade Ya!",
    "423": "Inspiration Manifestation",
    "424": "Equestria Games",
    "425": "Twilight's Kingdom - Part 1",
    "426": "Twilight's Kingdom - Part 2",
    "501": "The Cutie Map - Part 1",
    "502": "The Cutie Map - Part 2",
    "503": "Castle Sweet Castle",
    "504": "Bloom & Gloom",
    "505": "Tanks for the Memories",
    "506": "Appleoosa's Most Wanted",
    "507": "Make New Friends but Keep Discord",
    "508": "The Lost Treasure of Griffonstone",
    "509": "Slice of Life",
    "510": "Princess Spike",
    "511": "Party Pooped",
    "512": "Amending Fences",
    "513": "Do Princesses Dream of Magic Sheep?",
    "514": "Canterlot Boutique",
    "515": "Rarity Investigates!",
    "516": "Made in Manehattan",
    "517": "Brotherhooves Social",
    "518": "Crusaders of the Lost Mark",
    "519": "The One Where Pinkie Pie Knows",
    "520": "Hearthbreakers",
    "521": "Scare Master",
    "522": "What About Discord?",
    "523": "The Hooffields and McColts",
    "524": "The Mane Attraction",
    "525": "The Cutie Re-Mark - Part 1",
    "526": "The Cutie Re-Mark - Part 2",
    "601": "The Crystalling - Part 1",
    "602": "The Crystalling - Part 2",
    "603": "The Gift of the Maud Pie",
    "604": "On Your Marks",
    "605": "Gauntlet of Fire",
    "606": "No Second Prances",
    "607": "Newbie Dash",
    "608": "A Hearth's Warming Tail",
    "609": "The Saddle Row Review",
    "610": "Applejack's \"Day\" Off",
    "611": "Flutter Brutter",
    "612": "Spice Up Your Life",
    "613": "Stranger Than Fan Fiction",
    "614": "The Cart Before the Ponies",
    "615": "28 Pranks Later",
    "616": "The Times They Are A Changeling",
    "617": "Dungeons & Discords",
    "618": "Buckball Season",
    "619": "The Fault in Our Cutie Marks",
    "620": "Viva Las Pegasus",
    "621": "Every Little Thing She Does",
    "622": "P.P.O.V. (Pony Point of View)",
    "623": "Where the Apple Lies",
    "624": "Top Bolt",
    "625": "To Where and Back Again - Part 1",
    "626": "To Where and Back Again - Part 2",
    "701": "Celestial Advice",
    "702": "All Bottled Up",
    "703": "A Flurry of Emotions",
    "704": "Rock Solid Friendship",
    "705": "Fluttershy Leans In",
    "706": "Forever Filly",
    "707": "Parental Glideance",
    "708": "Hard to Say Anything",
    "709": "Honest Apple",
    "710": "A Royal Problem",
    "711": "Not Asking for Trouble",
    "712": "Discordant Harmony",
    "713": "The Perfect Pear",
    "714": "Fame and Misfortune",
    "715": "Triple Threat",
    "716": "Campfire Tales",
    "717": "To Change a Changeling",
    "718": "Daring Done?",
    "719": "It Isn't the Mane Thing About You",
    "720": "A Health of Information",
    "721": "Marks and Recreation",
    "722": "Once Upon a Zeppelin",
    "723": "Secrets and Pies",
    "724": "Uncommon Bond",
    "725": "Shadow Play - Part 1",
    "726": "Shadow Play - Part 2",
    "801": "School Daze - Part 1",
    "802": "School Daze - Part 2",
    "803": "The Maud Couple",
    "804": "Fake It 'Til You Make It",
    "805": "Grannies Gone Wild",
    "806": "Surf and or Turf",
    "807": "Horse Play",
    "808": "The Parent Map",
    "809": "Non-Compete Clause",
    "810": "The Break Up Break Down",
    "811": "Molt Down",
    "812": "Marks for Effort",
    "813": "The Mean 6",
    "814": "A Matter of Principals",
    "815": "The Hearth's Warming Club",
    "816": "Friendship University",
    "817": "The End in Friend",
    "818": "Yakity-Sax",
    "819": "Road to Friendship",
    "820": "The Washouts",
    "821": "A Rockhoof and a Hard Place",
    "822": "What Lies Beneath",
    "823": "Sounds of Silence",
    "824": "Father Knows Beast",
    "825": "School Raze - Part 1",
    "826": "School Raze - Part 2",
    "901": "The Beginning of the End - Part 1",
    "902": "The Beginning of the End - Part 2",
    "903": "Uprooted",
    "904": "Sparkle's Seven",
    "905": "The Point of No Return",
    "906": "Common Ground",
    "907": "She's All Yak",
    "908": "Frenemies",
    "909": "Sweet and Smoky",
    "910": "Going to Seed",
    "911": "Student Counsel",
    "912": "The Last Crusade",
    "913": "Between Dark and Dawn",
    "914": "The Last Laugh",
    "915": "2, 4, 6, Greaaat",
    "916": "A Trivial Pursuit",
    "917": "The Summer Sun Setback",
    "918": "She Talks to Angel",
    "919": "Dragon Dropped",
    "920": "A Horse Shoe-In",
    "921": "Daring Doubt",
    "922": "Growing Up is Hard to Do",
    "923": "The Big Mac Question",
    "924": "The Ending of the End - Part 1",
    "925": "The Ending of the End - Part 2",
    "926": "The Last Problem",
    "927": "A-Dressing Memories",
    "928": "Cakes for the Memories",
    "929": "Memnagerie",
    "930": "Deep Tissue Memories",
    "931": "Harvesting Memories",
    "932": "Memories and More"
}

class Buffer {
    constructor(length, size) {
        this.buffer = new Array(size);
        this.head = 0;
        this.tail = 0;
        this.maxLength = length;
        this.size = size;
        this.length = 0;
    }

    add(item) {
        if (this.length === this.size) throw new Error("Queue full");
        if (this.length === this.maxLength) {
            this.head = (this.head + 1) % this.size; // Overwrite the oldest item
        } else {
            this.length++;
        }
        this.buffer[this.tail] = item;
        this.tail = (this.tail + 1) % this.size;
    }

    dequeue() {
        if (this.length === 0) return undefined;
        const item = this.buffer[this.head];
        this.head = (this.head + 1) % this.size;
        this.length--;
        return item;
    }

    get contents() {
        let output = []
        for (let i = this.head; i !== this.tail; i = (i + 1) % this.size) {
            output.push(this.buffer[i]);
        }
        return output;
    }
}

function getLineData(line) {
    let epCode = line.slice(0, 3)
    let season = parseInt(line.slice(0, 1))
    let episode = parseInt(line.slice(1, 3))
    let title = titles[line.slice(0, 3)]
    let speakerID = parseInt(line.slice(3, 6), 16)
    let speaker = speakers[parseInt(line.slice(3, 6), 16)]
    let text = line.slice(6)
    return {
        epCode,
        season,
        episode,
        title,
        speakerID,
        speaker,
        text,
        formatLine: () => {
            if (speakerID) {
                return `    ${speaker}: ${text}`
            } else {
                return `    ${text}`
            }
        },
        formatEpisode: () => {
            return `Season ${season}, Episode ${episode} - ${title}`
        }
    }
}

const lineBuffer = new Buffer(5, 1000);
for await (const newLine of readLines(await Deno.open("transcript.txt"))) {
    lineBuffer.add(newLine);
    let target = lineBuffer.contents[3] || ""
    if (target.includes("train")) {
        let targetData = getLineData(target);
        console.log(targetData.formatEpisode());
        lineBuffer.contents.forEach(line => {
            console.log(getLineData(line).formatLine());
        })
    }
}